"""Multi-field catalog of olympiads, research, and competitions.

Upserted on every scraper run so listings stay fresh (update check via last_scraped_at).
Covers every OpportunityMap interest field.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime

from sqlalchemy.orm import Session

from app.models.enums import OpportunityType
from scraper.repository import ScrapedOpportunity, upsert_opportunity

logger = logging.getLogger(__name__)

SOURCE_NAME = "field_coverage_catalog"

OT = OpportunityType


def _item(
    *,
    external_id: str,
    title: str,
    url: str,
    description: str,
    opportunity_type: OpportunityType,
    field_slugs: list[str],
    application_url: str | None = None,
    grade_min: int = 9,
    grade_max: int = 12,
    grade_eligibility: str = "High School",
    experience: str | None = None,
    deadline_summary: str = "Deadlines vary by year and country — check the official site",
    deadline_at: datetime | None = None,
) -> ScrapedOpportunity:
    return ScrapedOpportunity(
        external_id=external_id,
        title=title,
        source_url=url,
        application_url=application_url or url,
        description=description,
        opportunity_type=opportunity_type,
        grade_eligibility=grade_eligibility,
        grade_min=grade_min,
        grade_max=grade_max,
        eligible_countries=None,
        experience_requirements=experience,
        deadline_at=deadline_at,
        deadline_summary=deadline_summary,
        field_slugs=field_slugs,
    )


# Broad automated catalog across AI, sciences, social science, writing, business, etc.
FIELD_COVERAGE: list[ScrapedOpportunity] = [
    # —— Mathematics ——
    _item(
        external_id="amc-12",
        title="AMC 12 (American Mathematics Competitions)",
        url="https://maa.org/student-programs/amc/",
        description="Leading US high-school math contest; gateway to AIME and USAMO.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        experience="Usually grades 9–12; school registration",
    ),
    _item(
        external_id="aime",
        title="American Invitational Mathematics Examination (AIME)",
        url="https://maa.org/math-competitions/american-invitational-mathematics-examination-aime",
        description="Invitation-only contest after strong AMC scores; path to USAMO.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        experience="Qualify via AMC 10/12",
    ),
    _item(
        external_id="usamo",
        title="USA Mathematical Olympiad (USAMO)",
        url="https://maa.org/math-competitions/usa-mathematical-olympiad-usamo",
        description="Top US proof-based olympiad; selects IMO team candidates.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        experience="Qualify via AMC + AIME",
    ),
    _item(
        external_id="promys",
        title="PROMYS (Program in Mathematics for Young Scientists)",
        url="https://promys.org/",
        description="Six-week number theory program at Boston University for high-school students.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["mathematics", "research"],
        deadline_summary="Applications typically due in March–April",
    ),
    _item(
        external_id="ross-mathematics",
        title="Ross Mathematics Program",
        url="https://rossprogram.org/",
        description="Intensive summer math program focused on number theory and proof.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["mathematics"],
    ),
    _item(
        external_id="hmmtt",
        title="Harvard-MIT Mathematics Tournament (HMMT)",
        url="https://www.hmmt.org/",
        description="Major team and individual high-school math tournament hosted by Harvard/MIT students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
    ),
    # —— Computer science / AI ——
    _item(
        external_id="usaco",
        title="USA Computing Olympiad (USACO)",
        url="https://usaco.org/",
        description="Online programming olympiad with Bronze–Platinum divisions; path toward IOI.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["computer-science", "ai"],
        grade_min=6,
    ),
    _item(
        external_id="codeforces-rounds",
        title="Codeforces Contests (High School Track)",
        url="https://codeforces.com/contests",
        description="Frequent rated programming contests used by olympiad students worldwide.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["computer-science"],
        grade_min=6,
        deadline_summary="Ongoing contest calendar — check Codeforces regularly",
    ),
    _item(
        external_id="google-code-jam-kickstart",
        title="Google Kick Start / Coding Competitions archive",
        url="https://codingcompetitions.withgoogle.com/",
        description="Google’s coding competition resources and practice archives for algorithmic problem solving.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["computer-science", "ai"],
    ),
    _item(
        external_id="mit-primes",
        title="MIT PRIMES",
        url="https://math.mit.edu/research/highschool/primes/",
        description="Year-long research mentorship in math, computer science, and computational biology.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["mathematics", "computer-science", "ai", "research", "biology"],
        deadline_summary="Applications typically open in fall for the following year",
    ),
    _item(
        external_id="rsi-css",
        title="Research Science Institute (RSI)",
        url="https://www.cee.org/programs/research-science-institute",
        description="Premier free summer research program at MIT for top high-school STEM students.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["research", "physics", "chemistry", "biology", "mathematics", "computer-science", "ai"],
        deadline_summary="US applications typically due mid-January",
    ),
    _item(
        external_id="ai-olympiad-ioai",
        title="International Olympiad in Artificial Intelligence (IOAI)",
        url="https://ioai-official.org/",
        description="International olympiad focused on AI concepts, algorithms, and applications for secondary students.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["ai", "computer-science"],
    ),
    # —— Physics / astronomy ——
    _item(
        external_id="uspho",
        title="USA Physics Olympiad (USAPhO)",
        url="https://www.aapt.org/physicsteam/2026/",
        description="US physics olympiad pathway toward the International Physics Olympiad.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["physics"],
    ),
    _item(
        external_id="fma",
        title="F=ma Contest (AAPT)",
        url="https://www.aapt.org/physicsteam/",
        description="Introductory US physics olympiad exam used to qualify for USAPhO.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["physics"],
    ),
    _item(
        external_id="ssp-astrophysics",
        title="Summer Science Program (SSP) — Astrophysics",
        url="https://www.summerscience.org/",
        description="Hands-on residential research program; astrophysics track includes asteroid orbit determination.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["physics", "research", "mathematics"],
    ),
    _item(
        external_id="iau-astronomy",
        title="International Astronomy Olympiad / national pathways",
        url="https://www.iau.org/",
        description="Astronomy olympiad opportunities via national astronomy education programs.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["physics"],
    ),
    # —— Chemistry ——
    _item(
        external_id="usnco",
        title="U.S. National Chemistry Olympiad (USNCO)",
        url="https://www.acs.org/education/olympiad.html",
        description="ACS chemistry olympiad; pathway to the International Chemistry Olympiad.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["chemistry"],
    ),
    _item(
        external_id="ssp-biochem",
        title="Summer Science Program (SSP) — Biochemistry",
        url="https://www.summerscience.org/",
        description="Residential SSP track focused on biochemistry and genomics research skills.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["chemistry", "biology", "research"],
    ),
    _item(
        external_id="acs-project-seed",
        title="ACS Project SEED",
        url="https://www.acs.org/education/students/highschool/seed.html",
        description="Summer chemistry research internships for economically disadvantaged high-school students.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["chemistry", "research"],
    ),
    # —— Biology / medicine ——
    _item(
        external_id="usabo",
        title="USA Biology Olympiad (USABO)",
        url="https://www.usabo-trc.org/",
        description="US biology olympiad pathway toward the International Biology Olympiad.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["biology"],
    ),
    _item(
        external_id="regeneron-sts",
        title="Regeneron Science Talent Search",
        url="https://www.societyforscience.org/regeneron-sts/",
        description="Prestigious US research competition for high-school seniors with original science projects.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["research", "biology", "chemistry", "physics", "engineering", "ai"],
        grade_min=12,
        grade_max=12,
        deadline_summary="Applications typically due in November for seniors",
    ),
    _item(
        external_id="simr-stanford",
        title="Stanford Institutes of Medicine Summer Research (SIMR)",
        url="https://med.stanford.edu/simr.html",
        description="Eight-week biomedical research internship for high-school students at Stanford Medicine.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["biology", "research", "chemistry"],
    ),
    _item(
        external_id="rockefeller-ssrp",
        title="Rockefeller University Summer Science Research Program",
        url="https://www.rockefeller.edu/education-and-training/high-school/",
        description="Summer biomedical research experience for high-school students in New York.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["biology", "research"],
    ),
    _item(
        external_id="nyu-arise",
        title="NYU Tandon ARISE",
        url="https://engineering.nyu.edu/research-innovation/student-research/arise",
        description="Applied research innovations program in science and engineering for NYC-area high schoolers.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["engineering", "research", "computer-science", "biology"],
    ),
    # —— Engineering / robotics ——
    _item(
        external_id="first-robotics",
        title="FIRST Robotics Competition",
        url="https://www.firstinspires.org/robotics/frc",
        description="Team robotics competition combining engineering design, coding, and outreach.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["engineering", "computer-science", "ai"],
        grade_min=9,
        deadline_summary="Season registration typically opens in fall",
    ),
    _item(
        external_id="first-tech-challenge",
        title="FIRST Tech Challenge",
        url="https://www.firstinspires.org/robotics/ftc",
        description="Modular robotics competition for grades 7–12.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["engineering", "computer-science"],
        grade_min=7,
    ),
    _item(
        external_id="science-olympiad",
        title="Science Olympiad",
        url="https://www.soinc.org/",
        description="Team STEM competition with events across biology, chemistry, physics, and engineering.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["biology", "chemistry", "physics", "engineering", "research"],
        grade_min=6,
    ),
    _item(
        external_id="cyberpatriot",
        title="CyberPatriot",
        url="https://www.uscyberpatriot.org/",
        description="National youth cyber defense competition teaching cybersecurity skills.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["computer-science", "engineering"],
        grade_min=6,
    ),
    # —— Economics / business ——
    _item(
        external_id="ieo",
        title="International Economics Olympiad (IEO)",
        url="https://ecolymp.org/",
        description="International olympiad in economics, finance, and business for secondary students.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["economics", "business"],
    ),
    _item(
        external_id="nec",
        title="National Economics Challenge (CEE)",
        url="https://www.councilforeconed.org/national-economics-challenge/",
        description="US team economics competition for high-school students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["economics"],
    ),
    _item(
        external_id="deca",
        title="DECA Competitive Events",
        url="https://www.deca.org/compete",
        description="Business, marketing, finance, and hospitality competitions for high-school DECA members.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["business", "economics"],
    ),
    _item(
        external_id="fbla",
        title="FBLA Competitive Events",
        url="https://www.fbla.org/compete/",
        description="Future Business Leaders of America contests across business and technology topics.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["business", "computer-science"],
    ),
    _item(
        external_id="wharton-ess",
        title="Wharton Global Youth — Essentials of Entrepreneurship / Leadership",
        url="https://globalyouth.wharton.upenn.edu/",
        description="Wharton programs introducing high-school students to business, finance, and entrepreneurship.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["business", "economics"],
    ),
    # —— Social science / humanities ——
    _item(
        external_id="ihbb",
        title="International History Bee & Bowl",
        url="https://www.historybowl.com/",
        description="International history quiz competitions for middle and high school students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["social-science"],
        grade_min=6,
    ),
    _item(
        external_id="nhsb",
        title="National History Bee & Bowl (US)",
        url="https://www.historybowl.com/",
        description="US history academic competitions leading to national championships.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["social-science"],
    ),
    _item(
        external_id="ipo-philosophy",
        title="International Philosophy Olympiad (IPO)",
        url="https://www.philosophy-olympiad.org/",
        description="Essay-based international olympiad in philosophy for secondary-school students.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["social-science", "writing"],
    ),
    _item(
        external_id="model-un",
        title="Model United Nations (global conferences)",
        url="https://www.un.org/en/mun",
        description="Debate and diplomacy simulations; many regional and international high-school conferences.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["social-science", "writing"],
        deadline_summary="Conference deadlines vary — browse regional MUN calendars",
    ),
    _item(
        external_id="nsda-debate",
        title="NSDA Speech & Debate",
        url="https://www.speechanddebate.org/",
        description="National Speech & Debate Association tournaments in policy, LD, PF, and speech events.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["social-science", "writing"],
    ),
    _item(
        external_id="psychology-olympiad",
        title="International Psychology Olympiad / national psychology contests",
        url="https://www.psychologyolympiad.org/",
        description="Psychology competitions introducing research methods and core psychology topics.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["social-science", "biology", "research"],
    ),
    # —— Writing / literature ——
    _item(
        external_id="scholastic-art-writing",
        title="Scholastic Art & Writing Awards",
        url="https://www.artandwriting.org/",
        description="Major US creative writing and arts awards for teens in grades 7–12.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["writing"],
        grade_min=7,
        deadline_summary="Regional deadlines typically fall/winter",
    ),
    _item(
        external_id="bennington-young-writers",
        title="Bennington Young Writers Awards",
        url="https://www.bennington.edu/center-for-the-advancement-of-public-action/young-writers-awards",
        description="Writing awards for poetry, fiction, and nonfiction by high-school students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["writing"],
    ),
    _item(
        external_id="princeton-poetry",
        title="Princeton University Poetry Contest for High School Students",
        url="https://arts.princeton.edu/",
        description="Competitive poetry contest hosted by Princeton for secondary-school writers.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["writing"],
    ),
    _item(
        external_id="profile-in-courage",
        title="John F. Kennedy Profile in Courage Essay Contest",
        url="https://www.jfklibrary.org/learn/education/profile-in-courage-essay-contest",
        description="National essay contest on political courage for US high-school students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["writing", "social-science"],
    ),
    # —— Research / summer STEM (multi-field) ——
    _item(
        external_id="garcia-stony-brook",
        title="Garcia Summer Program (Stony Brook)",
        url="https://www.stonybrook.edu/commcms/garcia/",
        description="Materials science and polymer research summer program for high-school students.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["chemistry", "engineering", "research", "physics"],
    ),
    _item(
        external_id="clark-scholars",
        title="Clark Scholars Program (Texas Tech)",
        url="https://www.depts.ttu.edu/honors/academicsandenrichment/affiliatedandhighschool/clarks/",
        description="Intensive summer research across STEM disciplines with faculty mentors.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["research", "engineering", "biology", "chemistry", "physics", "computer-science"],
    ),
    _item(
        external_id="iowa-sstp",
        title="University of Iowa Secondary Student Training Program (SSTP)",
        url="https://belinblank.education.uiowa.edu/students/sstp/",
        description="Residential research program pairing high-school students with UI faculty labs.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["research", "biology", "chemistry", "physics", "engineering", "ai"],
    ),
    _item(
        external_id="mites",
        title="MIT MITES / MOSTEC",
        url="https://oeop.mit.edu/programs/mites",
        description="MIT outreach STEM programs for underrepresented high-school students.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["engineering", "computer-science", "physics", "mathematics", "ai"],
    ),
    _item(
        external_id="yale-yygs",
        title="Yale Young Global Scholars (YYGS)",
        url="https://globalscholars.yale.edu/",
        description="Academic summer sessions spanning STEM, politics, literature, and social sciences.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["social-science", "writing", "research", "economics", "biology"],
    ),
    _item(
        external_id="telluride-tass",
        title="Telluride Association Summer Seminar (TASS)",
        url="https://www.tellurideassociation.org/",
        description="Free humanities and social science summer seminars for high-school students.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["social-science", "writing"],
    ),
    _item(
        external_id="bank-of-america-slc",
        title="Bank of America Student Leaders",
        url="https://about.bankofamerica.com/en/making-an-impact/student-leaders",
        description="Paid summer leadership internship with community nonprofits plus a Washington leadership summit.",
        opportunity_type=OT.FELLOWSHIP,
        field_slugs=["social-science", "business"],
    ),
    # —— Scholarships / fellowships with academic focus ——
    _item(
        external_id="questbridge",
        title="QuestBridge College Prep Scholars / National College Match",
        url="https://www.questbridge.org/",
        description="College access programs for high-achieving students from low-income backgrounds.",
        opportunity_type=OT.SCHOLARSHIP,
        field_slugs=["research", "social-science", "writing"],
        grade_min=11,
    ),
    _item(
        external_id="coca-cola-scholars",
        title="Coca-Cola Scholars Program",
        url="https://www.coca-colascholarsfoundation.org/",
        description="Merit scholarship for US high-school seniors with leadership and service.",
        opportunity_type=OT.SCHOLARSHIP,
        field_slugs=["social-science", "business"],
        grade_min=12,
        grade_max=12,
    ),
    _item(
        external_id="davidson-fellows",
        title="Davidson Fellows Scholarship",
        url="https://www.davidsongifted.org/fellows-scholarship/",
        description="Scholarships for students under 18 with significant projects in STEM, literature, music, or philosophy.",
        opportunity_type=OT.SCHOLARSHIP,
        field_slugs=["research", "mathematics", "physics", "chemistry", "biology", "ai", "writing", "social-science"],
        grade_min=6,
        grade_max=12,
    ),
    # —— Earth / environmental / geography ——
    _item(
        external_id="envirothon",
        title="NCF-Envirothon",
        url="https://envirothon.org/",
        description="Team environmental science competition covering soils, forestry, aquatics, wildlife, and current issues.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["biology", "social-science", "research"],
    ),
    _item(
        external_id="nasa-internships-hs",
        title="NASA Internships & Fellowships (High School)",
        url="https://intern.nasa.gov/",
        description="NASA internship portal including high-school eligible STEM opportunities when posted.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["physics", "engineering", "computer-science", "ai", "research"],
        deadline_summary="Sessions posted year-round — check NASA intern portal",
    ),
    _item(
        external_id="noaa-hollings-prep",
        title="NOAA education & high-school STEM opportunities",
        url="https://www.noaa.gov/education",
        description="NOAA education programs, contests, and pathways into earth and ocean sciences.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["biology", "physics", "research"],
    ),
    # —— India / international open contests often relevant worldwide ——
    _item(
        external_id="inmo",
        title="Indian National Mathematical Olympiad (INMO) pathway",
        url="https://olympiads.hbcse.tifr.res.in/mathematical-olympiad/",
        description="India’s math olympiad pathway (IOQM → RMO → INMO) toward IMO selection.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
    ),
    _item(
        external_id="incho",
        title="Indian National Chemistry Olympiad pathway (HBCSE)",
        url="https://olympiads.hbcse.tifr.res.in/chemistry-olympiad/",
        description="India chemistry olympiad selection pathway toward IChO.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["chemistry"],
    ),
    _item(
        external_id="inpho",
        title="Indian National Physics Olympiad pathway (HBCSE)",
        url="https://olympiads.hbcse.tifr.res.in/physics-olympiad/",
        description="India physics olympiad selection pathway toward IPhO.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["physics"],
    ),
    _item(
        external_id="inbo",
        title="Indian National Biology Olympiad pathway (HBCSE)",
        url="https://olympiads.hbcse.tifr.res.in/biology-olympiad/",
        description="India biology olympiad selection pathway toward IBO.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["biology"],
    ),
    _item(
        external_id="inao",
        title="Indian National Astronomy Olympiad pathway (HBCSE)",
        url="https://olympiads.hbcse.tifr.res.in/astronomy-olympiad/",
        description="India astronomy olympiad selection pathway toward IOAA.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["physics"],
    ),
    _item(
        external_id="zco-inoi",
        title="Indian Computing Olympiad (ZCO / INOI)",
        url="https://www.iarcs.org.in/inoi",
        description="India informatics olympiad pathway toward IOI.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["computer-science", "ai"],
    ),
    # —— Extra coverage: beginner → intermediate → selective, all fields ——
    # Mathematics (access → selective)
    _item(
        external_id="mathcounts",
        title="MATHCOUNTS",
        url="https://www.mathcounts.org/",
        description="School, chapter, state, and national math contest for middle-school students — strong on-ramp before AMC.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        grade_min=6,
        grade_max=8,
        experience="Open / beginner–intermediate; school teams",
        deadline_summary="School rounds typically fall–winter",
    ),
    _item(
        external_id="amc-10",
        title="AMC 10 (American Mathematics Competitions)",
        url="https://maa.org/student-programs/amc/",
        description="Entry US contest for grades 10 and below; qualifies strong scorers to AIME.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        grade_min=6,
        grade_max=10,
        experience="Open / intermediate",
    ),
    _item(
        external_id="purple-comet",
        title="Purple Comet! Math Meet",
        url="https://purplecomet.org/",
        description="Free online team math contest for middle and high school — approachable difficulty with mixed topics.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        grade_min=6,
        experience="Open / beginner-friendly",
    ),
    _item(
        external_id="math-prize-for-girls",
        title="Math Prize for Girls",
        url="https://mathprize.atfoundation.org/",
        description="Largest math prize contest for girls in North America, hosted at MIT.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        experience="Intermediate–selective registration",
    ),
    _item(
        external_id="pumac",
        title="Princeton University Mathematics Competition (PUMaC)",
        url="https://pumac.princeton.edu/",
        description="Team and individual high-school math tournament run by Princeton undergraduates.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        experience="Intermediate–advanced",
    ),
    _item(
        external_id="cmimc",
        title="Carnegie Mellon Informatics and Mathematics Competition (CMIMC)",
        url="https://cmimc.math.cmu.edu/",
        description="High-school contest covering math and computer science tracks.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics", "computer-science"],
        experience="Intermediate",
    ),
    _item(
        external_id="sumac",
        title="Stanford University Mathematics Camp (SUMaC)",
        url="https://sumac.stanford.edu/",
        description="Selective summer program exploring abstract algebra or algebraic topology.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["mathematics"],
        experience="Highly selective",
        deadline_summary="Applications typically due in February–March",
    ),
    _item(
        external_id="canada-usa-mathcamp",
        title="Canada/USA Mathcamp",
        url="https://www.mathcamp.org/",
        description="Five-week residential math summer program for students who love exploring advanced topics.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["mathematics", "research"],
        experience="Highly selective",
    ),
    _item(
        external_id="hcssim",
        title="Hampshire College Summer Studies in Mathematics (HCSSiM)",
        url="https://hcssim.org/",
        description="Six-week immersive math program emphasizing discovery and proof.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["mathematics"],
        experience="Selective",
    ),
    _item(
        external_id="brilliant-org-contests",
        title="Brilliant.org Weekly Contests & Courses",
        url="https://brilliant.org/",
        description="Ongoing problem-solving practice across math, science, and CS — low barrier on-ramp.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics", "physics", "computer-science", "ai"],
        grade_min=6,
        experience="Open / beginner-friendly",
        deadline_summary="Ongoing — weekly contests and courses",
    ),
    # Computer science / AI (access → selective)
    _item(
        external_id="picoctf",
        title="picoCTF",
        url="https://picoctf.org/",
        description="Beginner-friendly cybersecurity capture-the-flag contest from Carnegie Mellon.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["computer-science"],
        grade_min=6,
        experience="Open / beginner-friendly",
    ),
    _item(
        external_id="acsl",
        title="American Computer Science League (ACSL)",
        url="https://www.acsl.org/",
        description="Classroom-friendly CS contests covering programming, boolean algebra, and data structures.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["computer-science"],
        grade_min=6,
        experience="Open / intermediate; school teams",
    ),
    _item(
        external_id="congressional-app-challenge",
        title="Congressional App Challenge",
        url="https://www.congressionalappchallenge.us/",
        description="US student app-building contest judged by congressional districts — great first portfolio project.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["computer-science", "ai", "engineering"],
        experience="Open / beginner–intermediate",
        deadline_summary="Typically due in fall",
    ),
    _item(
        external_id="beaver-computing-challenge",
        title="Beaver Computing Challenge (CCC prep / CEMC)",
        url="https://cemc.uwaterloo.ca/contests/bcc.html",
        description="Accessible computational thinking contest from University of Waterloo CEMC.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["computer-science"],
        grade_min=6,
        experience="Open / beginner-friendly",
    ),
    _item(
        external_id="canadian-computing-competition",
        title="Canadian Computing Competition (CCC)",
        url="https://cemc.uwaterloo.ca/contests/computing.html",
        description="Programming contest with Junior and Senior divisions; pathway toward Canadian IOI team.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["computer-science"],
        experience="Intermediate–olympiad track",
    ),
    _item(
        external_id="girls-who-code-sip",
        title="Girls Who Code Summer Immersion Program",
        url="https://girlswhocode.com/programs/summer-immersion-program",
        description="Free or low-cost intro CS summer immersion for high-school girls and non-binary students.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["computer-science", "ai"],
        experience="Open / beginner-friendly (eligibility rules apply)",
    ),
    _item(
        external_id="kode-with-klossy",
        title="Kode With Klossy",
        url="https://www.kodewithklossy.com/",
        description="Tuition-free coding and AI camps for young women and gender-expansive teens.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["computer-science", "ai"],
        experience="Selective application; beginner–intermediate",
    ),
    _item(
        external_id="ai4all",
        title="AI4ALL / AI education programs",
        url="https://ai-4-all.org/",
        description="Programs introducing high-school students to artificial intelligence with an equity focus.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["ai", "computer-science"],
        experience="Selective; beginner–intermediate AI",
    ),
    _item(
        external_id="stanford-shtem",
        title="Stanford SHTEM Summer Program",
        url="https://shtem.stanford.edu/",
        description="Research-oriented summer exploring science, humanities, technology, engineering, and mathematics.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["ai", "computer-science", "engineering", "research", "social-science"],
        experience="Selective",
    ),
    _item(
        external_id="hackmit-programs",
        title="HackMIT / MIT high-school hackathons & outreach",
        url="https://hackmit.org/",
        description="Student-run MIT hackathon ecosystem; check HackMIT and related high-school events each year.",
        opportunity_type=OT.HACKATHON,
        field_slugs=["computer-science", "ai", "engineering"],
        experience="Open applications; intermediate builders thrive",
        deadline_summary="Event dates vary annually",
    ),
    _item(
        external_id="technovation-girls",
        title="Technovation Girls",
        url="https://www.technovation.org/",
        description="Global challenge where girls build mobile apps addressing real community problems.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["computer-science", "ai", "business"],
        grade_min=6,
        experience="Open / beginner–intermediate",
    ),
    # Physics / astronomy
    _item(
        external_id="physics-bowl",
        title="PhysicsBowl (AAPT)",
        url="https://www.aapt.org/Programs/contests/physicsbowl.cfm",
        description="Multiple-choice contest for high-school physics students — strong intermediate practice before olympiads.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["physics"],
        experience="Open / intermediate",
    ),
    _item(
        external_id="usaao",
        title="USA Astronomy & Astrophysics Olympiad (USAAAO)",
        url="https://usaao.org/",
        description="US astronomy olympiad pathway toward IOAA.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["physics"],
        experience="Selective national pathway",
    ),
    _item(
        external_id="perimeter-issyp",
        title="Perimeter Institute ISSYP",
        url="https://www.perimeterinstitute.ca/outreach/students/issyp",
        description="International Summer School for Young Physicists — theoretical physics immersion in Canada.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["physics", "mathematics", "research"],
        experience="Highly selective",
    ),
    _item(
        external_id="usayon",
        title="USA Young Physicists' Tournament / Physics Bowl pathway extras",
        url="https://www.aapt.org/Programs/contests/",
        description="AAPT contest hub linking PhysicsBowl and related high-school physics competitions.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["physics"],
        experience="Open / intermediate",
    ),
    # Chemistry
    _item(
        external_id="you-be-the-chemist",
        title="You Be The Chemist Challenge",
        url="https://www.chemed.org/programs/ybtc/",
        description="Accessible chemistry quiz challenge for middle-school students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["chemistry"],
        grade_min=6,
        grade_max=8,
        experience="Open / beginner",
    ),
    _item(
        external_id="chemagination",
        title="ACS Chemagination",
        url="https://www.acs.org/education/students/highschool/chemagination.html",
        description="Poster and essay contest imagining chemistry innovations 25 years in the future.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["chemistry", "writing"],
        experience="Open / intermediate",
    ),
    _item(
        external_id="canadian-chemistry-contest",
        title="Canadian Chemistry Contest (CCC / CIC)",
        url="https://www.cheminst.ca/",
        description="National chemistry contest supporting Canada’s olympiad pathway.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["chemistry"],
        experience="Intermediate–olympiad track",
    ),
    # Biology / medicine / health
    _item(
        external_id="brain-bee",
        title="International Brain Bee",
        url="https://thebrainbee.org/",
        description="Neuroscience competition for teens — local, national, and international rounds.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["biology", "research"],
        experience="Open local rounds → selective nationals",
    ),
    _item(
        external_id="hosa",
        title="HOSA – Future Health Professionals Competitive Events",
        url="https://hosa.org/",
        description="Health-science leadership and competition events spanning clinical, lab, and public-health topics.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["biology", "social-science"],
        experience="Open / chapter-based; many rigor levels",
    ),
    _item(
        external_id="genes-in-space",
        title="Genes in Space",
        url="https://www.genesinspace.org/",
        description="Contest for students to propose DNA experiments for the International Space Station.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["biology", "research", "engineering"],
        grade_min=7,
        experience="Open / intermediate; proposal-based",
    ),
    _item(
        external_id="biogeneius",
        title="BioGENEius Challenge",
        url="https://biotech.ca/education/biogeneius/",
        description="Biotechnology research competition for high-school projects with real biotech applications.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["biology", "research", "chemistry"],
        experience="Intermediate–selective (project required)",
    ),
    _item(
        external_id="jshs",
        title="Junior Science and Humanities Symposium (JSHS)",
        url="https://jshs.org/",
        description="Regional and national symposium where students present original STEM research.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["research", "biology", "chemistry", "physics", "engineering", "ai"],
        experience="Intermediate–selective (research project)",
    ),
    _item(
        external_id="broad-summer-scholars",
        title="Broad Summer Scholars Program",
        url="https://www.broadinstitute.org/bssp",
        description="Summer research at the Broad Institute for local high-school students in genomics and biomedicine.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["biology", "research", "ai", "computer-science"],
        experience="Selective; typically New England students",
    ),
    _item(
        external_id="jackson-lab-summer",
        title="Jackson Laboratory Summer Student Program",
        url="https://www.jax.org/education-and-learning/high-school-students-and-undergraduates/summer-student-program",
        description="Genetics and genomics research summer for high-school and undergraduate students.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["biology", "research"],
        experience="Highly selective",
    ),
    _item(
        external_id="bu-rise",
        title="Boston University RISE",
        url="https://www.bu.edu/summer/high-school-programs/rise/",
        description="Six-week research internship in BU labs across STEM disciplines.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["research", "biology", "chemistry", "physics", "engineering", "computer-science"],
        experience="Selective",
    ),
    _item(
        external_id="simons-summer",
        title="Simons Summer Research Program (Stony Brook)",
        url="https://www.stonybrook.edu/simons/",
        description="Hands-on research with Stony Brook faculty mentors for high-school students.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["research", "biology", "physics", "chemistry", "mathematics", "computer-science"],
        experience="Highly selective",
    ),
    # Engineering / robotics / inventing
    _item(
        external_id="vex-robotics",
        title="VEX Robotics Competition",
        url="https://www.vexrobotics.com/competition",
        description="Classroom-to-competition robotics with VEX IQ and VEX V5 platforms.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["engineering", "computer-science"],
        grade_min=6,
        experience="Open / intermediate; team-based",
    ),
    _item(
        external_id="tsa-competitions",
        title="Technology Student Association (TSA) Competitions",
        url="https://tsaweb.org/",
        description="Dozens of engineering, coding, design, and leadership events for middle and high school.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["engineering", "computer-science", "ai"],
        grade_min=6,
        experience="Open / chapter-based; mixed rigor",
    ),
    _item(
        external_id="mate-rov",
        title="MATE ROV Competition",
        url="https://materovcompetition.org/",
        description="Underwater robotics competition designing remotely operated vehicles for ocean missions.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["engineering", "physics", "computer-science"],
        experience="Intermediate–advanced; team-based",
    ),
    _item(
        external_id="conrad-challenge",
        title="Conrad Challenge",
        url="https://www.conradchallenge.org/",
        description="Innovation and entrepreneurship challenge for student teams solving real-world problems.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["engineering", "business", "ai", "research"],
        experience="Open application; intermediate–selective finals",
    ),
    _item(
        external_id="odyssey-of-the-mind",
        title="Odyssey of the Mind",
        url="https://www.odysseyofthemind.com/",
        description="Creative problem-solving competition blending engineering, performance, and design.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["engineering", "writing", "social-science"],
        grade_min=6,
        experience="Open / beginner–intermediate",
    ),
    _item(
        external_id="solar-car-challenge",
        title="Solar Car Challenge",
        url="https://www.solarcarchallenge.org/",
        description="High-school teams design, build, and race solar-powered cars.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["engineering", "physics"],
        experience="Intermediate–advanced; multi-year team projects",
    ),
    # Economics / business
    _item(
        external_id="personal-finance-challenge",
        title="National Personal Finance Challenge",
        url="https://financechallenge.unl.edu/",
        description="Team competition on budgeting, investing, credit, and financial literacy.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["economics", "business"],
        experience="Open / beginner–intermediate",
    ),
    _item(
        external_id="fed-challenge",
        title="Fed Challenge / College Fed Challenge (HS variants by district)",
        url="https://www.federalreserve.gov/econres/feds/fed-challenge.htm",
        description="Monetary-policy presentation contests run through Federal Reserve districts — check local HS offerings.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["economics"],
        experience="Intermediate–selective",
    ),
    _item(
        external_id="wharton-investment-competition",
        title="Wharton Global High School Investment Competition",
        url="https://globalyouth.wharton.upenn.edu/contests-competitions/investment-competition/",
        description="Team investing simulation and analysis contest from Wharton Global Youth.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["business", "economics"],
        experience="Open registration; competitive finals",
    ),
    _item(
        external_id="diamond-challenge",
        title="Diamond Challenge for High School Entrepreneurs",
        url="https://diamondchallenge.org/",
        description="Global entrepreneurship competition for high-school startups and social ventures.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["business", "economics"],
        experience="Open / intermediate; pitch-based",
    ),
    _item(
        external_id="nfte",
        title="Network for Teaching Entrepreneurship (NFTE)",
        url="https://www.nfte.com/",
        description="Entrepreneurship education and pitch competitions for high-school students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["business"],
        experience="Open via NFTE programs",
    ),
    _item(
        external_id="blue-ocean-competition",
        title="Blue Ocean High School Entrepreneurship Competition",
        url="https://blueoceancompetition.org/",
        description="Global pitch competition applying Blue Ocean Strategy to student ventures.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["business"],
        experience="Open / intermediate",
    ),
    _item(
        external_id="junior-achievement",
        title="Junior Achievement Company Program / Competitions",
        url="https://jausa.ja.org/",
        description="Hands-on business programs and competitions teaching entrepreneurship and financial literacy.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["business", "economics"],
        grade_min=6,
        experience="Open / beginner-friendly",
    ),
    # Social science / humanities / debate
    _item(
        external_id="world-scholars-cup",
        title="World Scholar's Cup",
        url="https://www.worldscholarscup.com/",
        description="Team academic tournament mixing debate, writing, quiz, and collaborative challenges.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["social-science", "writing"],
        grade_min=6,
        experience="Open / intermediate",
    ),
    _item(
        external_id="we-the-people",
        title="We the People: The Citizen and the Constitution",
        url="https://www.civiced.org/we-the-people",
        description="Civics competition where teams testify on constitutional topics before simulated hearings.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["social-science", "writing"],
        experience="School/class-based; intermediate",
    ),
    _item(
        external_id="mock-trial",
        title="High School Mock Trial (state / national)",
        url="https://www.nationalmocktrial.org/",
        description="Courtroom simulation competitions developing legal reasoning, public speaking, and teamwork.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["social-science", "writing"],
        experience="Open via school teams; competitive at state/nationals",
    ),
    _item(
        external_id="ethics-bowl",
        title="National High School Ethics Bowl",
        url="https://nhseb.unc.edu/",
        description="Collaborative ethics case competition emphasizing reasoned dialogue over debate scoring.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["social-science", "writing"],
        experience="Open / intermediate",
    ),
    _item(
        external_id="euro-challenge",
        title="Euro Challenge",
        url="https://www.euro-challenge.org/",
        description="Economics and EU current-events team competition for US high-school students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["economics", "social-science"],
        grade_min=9,
        grade_max=10,
        experience="Open / intermediate",
    ),
    _item(
        external_id="national-geographic-bee",
        title="National Geographic GeoBee / geography contests",
        url="https://www.nationalgeographic.org/education/",
        description="Geography knowledge contests and National Geographic education challenges for students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["social-science"],
        grade_min=6,
        experience="Open / beginner–intermediate",
    ),
    _item(
        external_id="harvard-model-congress",
        title="Harvard Model Congress",
        url="https://www.harvardmodelcongress.org/",
        description="Large student government simulation conferences hosted by Harvard undergraduates.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["social-science", "writing"],
        experience="Open registration; intermediate–advanced debate prep helps",
    ),
    # Writing / journalism / essays
    _item(
        external_id="nyt-student-editorial",
        title="New York Times Student Editorial Contest",
        url="https://www.nytimes.com/spotlight/learning-student-contests",
        description="Open editorial-writing contest for teenagers; strong intermediate writing opportunity.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["writing", "social-science"],
        experience="Open / intermediate",
        deadline_summary="Typically winter–spring — check NYT Learning Network",
    ),
    _item(
        external_id="foyle-young-poets",
        title="Foyle Young Poets of the Year Award",
        url="https://foyleyoungpoets.org/",
        description="Major international poetry competition for writers aged 11–17.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["writing"],
        grade_min=6,
        experience="Open / intermediate–selective winners",
    ),
    _item(
        external_id="john-locke-essay",
        title="John Locke Institute Essay Competition",
        url="https://www.johnlockeinstitute.com/essay-competition",
        description="Global essay contest across philosophy, politics, economics, history, psychology, theology, and law.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["writing", "social-science", "economics"],
        experience="Open entry; highly competitive shortlist",
    ),
    _item(
        external_id="concord-review",
        title="The Concord Review",
        url="https://www.tcr.org/",
        description="Quarterly journal publishing exemplary history research essays by high-school students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["writing", "social-science", "research"],
        experience="Selective publication standard",
    ),
    _item(
        external_id="letters-about-literature",
        title="Letters About Literature",
        url="https://www.arts.gov/",
        description="Reader-response letter contest (when offered by state libraries / partners) for grades 4–12.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["writing"],
        grade_min=6,
        experience="Open / beginner–intermediate",
    ),
    _item(
        external_id="patricia-grodd-poetry",
        title="Patricia Grodd Poetry Contest for Young Writers (Kenyon Review)",
        url="https://kenyonreview.org/contests/",
        description="Poetry contest for high-school writers with publication in the Kenyon Review.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["writing"],
        experience="Open / selective winners",
    ),
    _item(
        external_id="teen-ink",
        title="Teen Ink Contests & Magazine",
        url="https://www.teenink.com/",
        description="Ongoing publication and contest platform for teen writing, art, and opinions.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["writing"],
        grade_min=6,
        experience="Open / beginner-friendly",
        deadline_summary="Rolling submissions and themed contests",
    ),
    # Research / science fairs (access → elite)
    _item(
        external_id="regeneron-isef-affiliates",
        title="Society for Science — affiliated science fairs (path to ISEF)",
        url="https://www.societyforscience.org/isef/about/find-a-fair/",
        description="Find local and regional fairs that qualify projects toward Regeneron ISEF.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["research", "biology", "chemistry", "physics", "engineering", "ai"],
        grade_min=6,
        experience="Open local fairs → selective nationals",
        deadline_summary="Regional fair deadlines vary widely",
    ),
    _item(
        external_id="google-science-fair-archive",
        title="Google Science Fair / Young Scientist Challenge pathways",
        url="https://www.googlesciencefair.com/",
        description="Legacy Google Science Fair resources plus related young scientist challenges for project-based STEM.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["research", "engineering", "ai"],
        experience="Open / intermediate project work",
    ),
    _item(
        external_id="ucsb-rmp",
        title="UC Santa Barbara Research Mentorship Program (RMP)",
        url="https://www.summer.ucsb.edu/programs/research-mentorship-program-rmp",
        description="Summer research mentorship pairing high-school students with UCSB researchers.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["research", "biology", "chemistry", "physics", "engineering", "computer-science"],
        experience="Selective",
    ),
    _item(
        external_id="ucsc-sip",
        title="UC Santa Cruz Science Internship Program (SIP)",
        url="https://sip.ucsc.edu/",
        description="Summer research internships in STEM labs for high-school students.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["research", "biology", "physics", "chemistry", "computer-science", "ai"],
        experience="Selective",
    ),
    _item(
        external_id="penn-lrsm-summer",
        title="Penn LRSM / materials research high-school programs",
        url="https://www.lrsm.upenn.edu/",
        description="University of Pennsylvania materials science outreach and summer research options for high-school students.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["chemistry", "physics", "engineering", "research"],
        experience="Selective",
    ),
    _item(
        external_id="smith-summer-science",
        title="Smith College Summer Science and Engineering Program",
        url="https://www.smith.edu/academics/precollege/ssep",
        description="Research-rich summer STEM program for high-school girls.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["research", "biology", "chemistry", "engineering", "physics"],
        experience="Selective",
    ),
    # India / South Asia accessible + selective
    _item(
        external_id="iris-national-fair",
        title="IRIS National Fair (India)",
        url="https://www.irisnationalfair.org/",
        description="India’s affiliated science fair pathway toward Regeneron ISEF.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["research", "biology", "chemistry", "physics", "engineering", "ai"],
        experience="Open regional → selective national",
    ),
    _item(
        external_id="atl-marathon",
        title="ATL Marathon (Atal Tinkering Labs)",
        url="https://aim.gov.in/",
        description="Innovation marathon for students in Atal Tinkering Labs across India.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["engineering", "ai", "computer-science", "business"],
        grade_min=6,
        experience="Open via ATL schools; beginner–intermediate",
    ),
    _item(
        external_id="sof-olympiads",
        title="SOF Olympiads (IMO, NSO, NCO, IGKO, etc.)",
        url="https://sofworld.org/",
        description="School-level olympiads across math, science, computing, English, and general knowledge — accessible on-ramp.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics", "physics", "chemistry", "biology", "computer-science", "social-science"],
        grade_min=6,
        experience="Open / beginner-friendly",
    ),
    _item(
        external_id="technothlon",
        title="Technothlon (IIT Guwahati)",
        url="https://techniche.org/technothlon",
        description="School championship examining logic, puzzle-solving, and technical aptitude.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics", "engineering", "computer-science"],
        grade_min=6,
        experience="Open / intermediate",
    ),
    _item(
        external_id="inspire-manak",
        title="INSPIRE Awards – MANAK",
        url="https://www.inspireawards-dst.gov.in/",
        description="India DST program recognizing original ideas and innovations from school students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["research", "engineering", "biology", "chemistry", "physics"],
        grade_min=6,
        experience="Open via schools",
    ),
    _item(
        external_id="ntse-india",
        title="National Talent Search Examination (NTSE) / successor state schemes",
        url="https://ncert.nic.in/",
        description="Historic national talent search exam; check NCERT/state updates for current scholarship pathways.",
        opportunity_type=OT.SCHOLARSHIP,
        field_slugs=["mathematics", "social-science", "research"],
        grade_min=10,
        grade_max=10,
        experience="Selective national exam (status varies by year)",
    ),
    # Multi-field summer / fellowships of varying selectivity
    _item(
        external_id="launchx",
        title="LaunchX Entrepreneurship Programs",
        url="https://www.launchx.com/",
        description="Entrepreneurship programs helping high-school students start real companies.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["business", "engineering", "ai"],
        experience="Selective",
    ),
    _item(
        external_id="bank-of-america-student-leaders-note",
        title="Local nonprofit summer fellowships (search via LeadAmerica / similar)",
        url="https://www.leadamerica.org/",
        description="Leadership conferences and civic programs for high-school students interested in public service and social impact.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["social-science", "business"],
        experience="Open–selective depending on program",
    ),
    _item(
        external_id="berkeley-business-academy",
        title="Berkeley Business Academy for Youth (B-BAY)",
        url="https://haas.berkeley.edu/community/bbay/",
        description="Haas School summer business academy introducing strategy, marketing, and entrepreneurship.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["business", "economics"],
        experience="Selective",
    ),
    _item(
        external_id="peterhouse-kelvin",
        title="Peterhouse Kelvin Science Prize / Cambridge essay prizes",
        url="https://www.pet.cam.ac.uk/",
        description="Cambridge college essay and science prizes open to secondary-school students worldwide.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["writing", "physics", "chemistry", "biology", "mathematics"],
        experience="Open entry; selective recognition",
    ),    _item(
        external_id="isee-math-counts-bridge",
        title="Art of Problem Solving Online Contests & Classes",
        url="https://artofproblemsolving.com/",
        description="AoPS contests (including WOOT prep culture) and classes spanning beginner AMC through olympiad training.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        grade_min=6,
        experience="Open paid/free mix; beginner → olympiad rigor",
        deadline_summary="Ongoing contest and class calendar",
    ),
]


def seed_field_coverage_catalog(db: Session) -> dict[str, int]:
    """Upsert multi-field catalog entries (automated update check each run)."""
    stats = {"listed": 0, "created": 0, "updated": 0, "skipped": 0, "no_deadline": 0}

    items = FIELD_COVERAGE
    stats["listed"] = len(items)
    logger.info("Seeding %s — %s opportunit(ies)", SOURCE_NAME, len(items))

    for index, item in enumerate(items, start=1):
        try:
            if item.deadline_at is None:
                stats["no_deadline"] += 1
            _, created = upsert_opportunity(db, item, source_name=SOURCE_NAME)
            if created:
                stats["created"] += 1
            else:
                stats["updated"] += 1
            logger.info(
                "[%s/%s] %s %s",
                index,
                len(items),
                "CREATED" if created else "UPDATED",
                item.title,
            )
        except Exception:
            stats["skipped"] += 1
            logger.exception("Failed to seed %s", item.external_id)

    return stats
