"""Solid curated catalog of real high-school programs worldwide.

Olympiads, competitions, summer schools, scholarships, fellowships, and research
placements across STEM, writing, social science, business, and AI. Upserted on
every scraper run. Every entry sets eligible_countries explicitly ([] = worldwide)
and prefers a concrete 2026 deadline_at.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime

from sqlalchemy.orm import Session

from app.models.enums import OpportunityType
from scraper.repository import ScrapedOpportunity, upsert_opportunity

logger = logging.getLogger(__name__)

SOURCE_NAME = "solid_programs_catalog"

OT = OpportunityType

EU = [
    "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GR",
    "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT", "RO", "SK",
    "SI", "ES", "SE",
]


def _dt(y: int, m: int, d: int) -> datetime:
    return datetime(y, m, d, 23, 59, 59, tzinfo=UTC)


def _item(
    *,
    external_id: str,
    title: str,
    url: str,
    description: str,
    opportunity_type: OpportunityType,
    field_slugs: list[str],
    eligible_countries: list[str],
    application_url: str | None = None,
    grade_min: int = 9,
    grade_max: int = 12,
    grade_eligibility: str = "High School",
    experience: str | None = None,
    deadline_summary: str = "Deadlines vary by year and country — check the official site",
    deadline_at: datetime | None = None,
) -> ScrapedOpportunity:
    return ScrapedOpportunity(
        external_id=external_id,
        title=title,
        source_url=url,
        application_url=application_url or url,
        description=description,
        opportunity_type=opportunity_type,
        grade_eligibility=grade_eligibility,
        grade_min=grade_min,
        grade_max=grade_max,
        eligible_countries=eligible_countries,
        experience_requirements=experience,
        deadline_at=deadline_at,
        deadline_summary=deadline_summary,
        field_slugs=field_slugs,
    )


SOLID_PROGRAMS_CATALOG: list[ScrapedOpportunity] = [
    # —— Mathematics ——
    _item(
        external_id="ukmt-junior-mathematical-challenge-2026",
        title="UKMT Junior Mathematical Challenge",
        url="https://www.ukmt.org.uk/",
        description="UK Mathematics Trust multiple-choice challenge for younger secondary students; gateway to follow-on olympiad rounds.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        eligible_countries=["GB"],
        grade_min=7,
        grade_max=10,
        experience="Open via UK schools",
        deadline_at=_dt(2026, 4, 28),
        deadline_summary="Typically late April (UK school registration)",
    ),
    _item(
        external_id="ukmt-intermediate-mathematical-challenge-2026",
        title="UKMT Intermediate Mathematical Challenge",
        url="https://www.ukmt.org.uk/",
        description="UKMT challenge for intermediate secondary students leading toward Kangaroo and olympiad papers.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        eligible_countries=["GB"],
        grade_min=9,
        grade_max=11,
        experience="Open via UK schools",
        deadline_at=_dt(2026, 2, 4),
        deadline_summary="Typically early February",
    ),
    _item(
        external_id="british-mathematical-olympiad-2026",
        title="British Mathematical Olympiad (BMO)",
        url="https://bmo.maths.org/",
        description="UK proof-based olympiad selecting candidates for IMO training; Round 1 and Round 2 papers.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["GB"],
        experience="Invite via UKMT Senior Challenge / mentoring",
        deadline_at=_dt(2026, 11, 20),
        deadline_summary="Round 1 typically late November",
    ),
    _item(
        external_id="canadian-open-math-challenge-2026",
        title="Canadian Open Mathematics Challenge (COMC)",
        url="https://cms.math.ca/competitions/comc/",
        description="Canadian Mathematical Society national contest; pathway toward the Canadian Mathematical Olympiad.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        eligible_countries=["CA"],
        grade_min=7,
        experience="Open via Canadian schools",
        deadline_at=_dt(2026, 10, 29),
        deadline_summary="Typically late October",
    ),
    _item(
        external_id="euclid-contest-waterloo-2026",
        title="Euclid Contest (CEMC)",
        url="https://www.cemc.uwaterloo.ca/contests/euclid.html",
        description="University of Waterloo's premier Grade 12 mathematics contest, widely used for university admissions signaling.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        eligible_countries=["CA", "US"],
        experience="Open; advanced high-school math",
        deadline_at=_dt(2026, 4, 8),
        deadline_summary="Typically early April",
    ),
    _item(
        external_id="amc-8-2026",
        title="AMC 8 (American Mathematics Competitions)",
        url="https://maa.org/student-programs/amc/",
        application_url="https://maa.org/amcreg/",
        description="MAA middle-school math contest emphasizing creative problem-solving for grades 8 and below.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        eligible_countries=["US"],
        grade_min=6,
        grade_max=8,
        experience="Open via school registration",
        deadline_at=_dt(2026, 1, 22),
        deadline_summary="Contest window typically mid-to-late January",
    ),
    _item(
        external_id="asian-pacific-math-olympiad-2026",
        title="Asian Pacific Mathematics Olympiad (APMO)",
        url="https://www.apmo-official.org/",
        description="Regional proof olympiad for Pacific Rim countries; often used as an IMO team selection contest.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["AU", "CN", "SG", "IN", "JP", "KR", "NZ", "PH", "TH", "VN", "MY", "ID", "HK", "TW"],
        experience="National team / olympiad program nomination",
        deadline_at=_dt(2026, 3, 10),
        deadline_summary="Contest typically March; national deadlines earlier",
    ),
    _item(
        external_id="tournament-of-towns-2026",
        title="Tournament of Towns",
        url="https://www.math.toronto.edu/toz/",
        description="International proof-based math tournament with Fall and Spring rounds; organized via local organizing towns.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        eligible_countries=[],
        experience="Open via local Tournament of Towns organizers",
        deadline_at=_dt(2026, 10, 4),
        deadline_summary="Fall round typically early October; Spring round in spring",
    ),
    _item(
        external_id="duke-math-meet-2026",
        title="Duke Math Meet (DMM)",
        url="https://math.duke.edu/duke-math-meet",
        description="Team and individual high-school math contest hosted by Duke University math students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        eligible_countries=["US"],
        experience="Open team registration",
        deadline_at=_dt(2026, 11, 7),
        deadline_summary="Typically November contest weekend",
    ),
    _item(
        external_id="mandelbrot-competition-2026",
        title="Mandelbrot Competition",
        url="https://www.mandelbrot.org/",
        description="Multi-round individual mathematics competition for high-school students emphasizing deep problem-solving.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        eligible_countries=["US", "CA"],
        experience="Open / intermediate–advanced",
        deadline_at=_dt(2026, 10, 15),
        deadline_summary="Round schedule posted each fall",
    ),
    _item(
        external_id="hypatia-contest-cemc-2026",
        title="Hypatia Contest (CEMC)",
        url="https://www.cemc.uwaterloo.ca/contests/hypatia.html",
        description="CEMC Grade 11 contest from the University of Waterloo, part of the Fryer/Galois/Hypatia suite.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        eligible_countries=["CA", "US"],
        grade_min=10,
        grade_max=11,
        experience="Open via schools",
        deadline_at=_dt(2026, 4, 15),
        deadline_summary="Typically mid-April",
    ),
    _item(
        external_id="obmep-brazil-2026",
        title="Brazilian Math Olympiad of Public Schools (OBMEP)",
        url="https://www.obmep.org.br/",
        description="Large-scale Brazilian mathematics olympiad for public-school students with national medals and research awards.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["BR"],
        grade_min=6,
        experience="Open to Brazilian public-school students",
        deadline_at=_dt(2026, 5, 20),
        deadline_summary="First phase typically May–June",
    ),
    _item(
        external_id="rmo-india-2026",
        title="Regional Mathematical Olympiad (RMO) India",
        url="https://olympiads.hbcse.tifr.res.in/",
        description="India's regional olympiad stage after IOQM; selects students for INMO and the IMO training pipeline.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["IN"],
        experience="Qualify via IOQM",
        deadline_at=_dt(2026, 11, 1),
        deadline_summary="Typically October–November after IOQM",
    ),
    _item(
        external_id="singapore-mathematical-olympiad-junior-2026",
        title="Singapore Mathematical Olympiad (Junior Section)",
        url="https://sms.math.nus.edu.sg/smo/",
        description="Singapore Mathematical Society olympiad junior section for secondary students.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["SG"],
        grade_min=7,
        grade_max=10,
        experience="Open via Singapore schools",
        deadline_at=_dt(2026, 5, 30),
        deadline_summary="Typically May–June",
    ),
    _item(
        external_id="amesa-maths-challenge-2026",
        title="AMESA Mathematics Challenge (South Africa)",
        url="https://www.amesa.org.za/",
        description="Association for Mathematics Education of South Africa challenge for school learners nationwide.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        eligible_countries=["ZA"],
        grade_min=4,
        grade_max=12,
        experience="Open via South African schools",
        deadline_at=_dt(2026, 5, 15),
        deadline_summary="School rounds typically in May",
    ),
    # —— Computer science / AI ——
    _item(
        external_id="bebras-computing-challenge-2026",
        title="Bebras Computing Challenge",
        url="https://www.bebras.org/",
        description="International informatics challenge promoting computational thinking for school students of all ages.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["computer-science"],
        eligible_countries=[],
        grade_min=3,
        experience="Open via national Bebras organizers",
        deadline_at=_dt(2026, 11, 9),
        deadline_summary="International Bebras week typically mid-November",
    ),
    _item(
        external_id="atcoder-beginner-contests-2026",
        title="AtCoder Beginner Contests",
        url="https://atcoder.jp/",
        description="Regular rated programming contests popular with olympiad and competitive-programming students worldwide.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["computer-science", "ai"],
        eligible_countries=[],
        grade_min=6,
        experience="Open online; beginner → advanced",
        deadline_at=None,
        deadline_summary="Weekly/biweekly contest calendar — ongoing",
    ),
    _item(
        external_id="ncwit-aspirations-award-2026",
        title="NCWIT Award for Aspirations in Computing",
        url="https://www.aspirations.org/",
        description="National recognition and scholarships for high-school women, genderqueer, and non-binary students in computing.",
        opportunity_type=OT.SCHOLARSHIP,
        field_slugs=["computer-science", "ai"],
        eligible_countries=["US", "CA", "PR", "GU", "VI", "AS", "MP"],
        experience="Open to eligible high-school students in computing",
        deadline_at=_dt(2026, 11, 5),
        deadline_summary="National application typically due early November",
    ),
    _item(
        external_id="ioitc-india-2026",
        title="International Olympiad in Informatics Training Camp (India)",
        url="https://www.iarcs.org.in/",
        description="IARCS/IOI India training pathway after ZCO/INOI for selecting India's IOI team.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["computer-science"],
        eligible_countries=["IN"],
        experience="Qualify via ZCO / INOI",
        deadline_at=_dt(2026, 1, 15),
        deadline_summary="ZCO typically December–January; training camp follows INOI",
    ),
    _item(
        external_id="singapore-computing-olympiad-noi-2026",
        title="National Olympiad in Informatics (Singapore)",
        url="https://noi.sg/",
        description="Singapore's national informatics olympiad selecting candidates for IOI training.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["computer-science"],
        eligible_countries=["SG"],
        experience="Open to Singapore secondary/JC students",
        deadline_at=_dt(2026, 3, 7),
        deadline_summary="Typically March contest",
    ),
    _item(
        external_id="european-girls-olympiad-informatics-2026",
        title="European Girls' Olympiad in Informatics (EGOI)",
        url="https://egoi.org/",
        description="International informatics olympiad for young women; national teams compete in algorithmic programming.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["computer-science"],
        eligible_countries=EU + ["GB", "CH", "NO", "IS", "TR", "UA"],
        experience="National team selection",
        deadline_at=_dt(2026, 4, 15),
        deadline_summary="Contest typically July; national selection earlier",
    ),
    # —— Biology ——
    _item(
        external_id="canadian-biology-olympiad-2026",
        title="Canadian Biology Olympiad (CBO)",
        url="https://www.biolympiads.ca/",
        description="National biology olympiad selecting Canada's IBO team through exams and a training camp.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["biology"],
        eligible_countries=["CA"],
        experience="Open national exam; advanced biology",
        deadline_at=_dt(2026, 4, 20),
        deadline_summary="National exam typically April",
    ),
    _item(
        external_id="singapore-biology-olympiad-2026",
        title="Singapore Biology Olympiad (SBO)",
        url="https://www.sbo.sg/",
        description="National biology olympiad for Singapore JC/secondary students toward IBO selection.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["biology"],
        eligible_countries=["SG"],
        experience="School nomination / open rounds",
        deadline_at=_dt(2026, 1, 31),
        deadline_summary="Theoretical round typically January–February",
    ),
    _item(
        external_id="australian-biology-olympiad-aso-2026",
        title="Australian Science Olympiad — Biology",
        url="https://www.aso.edu.au/",
        description="Australian Science Olympiad biology exam leading to summer school and IBO team selection.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["biology"],
        eligible_countries=["AU"],
        experience="Open via Australian Science Olympiad exams",
        deadline_at=_dt(2026, 8, 5),
        deadline_summary="Exam typically August",
    ),
    _item(
        external_id="south-african-biology-olympiad-2026",
        title="South African Biology Olympiad",
        url="https://www.saasta.ac.za/",
        description="National biology olympiad pathway under SAASTA for South African secondary learners.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["biology"],
        eligible_countries=["ZA"],
        experience="Open via schools",
        deadline_at=_dt(2026, 5, 22),
        deadline_summary="School rounds typically May",
    ),
    _item(
        external_id="brazilian-biology-olympiad-obr-2026",
        title="Brazilian Biology Olympiad (OBB)",
        url="https://olimpiadasdebiologia.butantan.gov.br/",
        description="National Brazilian biology olympiad organized with Instituto Butantan support.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["biology"],
        eligible_countries=["BR"],
        experience="Open via Brazilian schools",
        deadline_at=_dt(2026, 6, 15),
        deadline_summary="Phases typically mid-year",
    ),
    _item(
        external_id="european-union-science-olympiad-euso-2026",
        title="European Union Science Olympiad (EUSO)",
        url="https://euso.eu/",
        description="Team science olympiad for EU secondary students integrating biology, chemistry, and physics experiments.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["biology", "chemistry", "physics"],
        eligible_countries=EU,
        experience="National team of three under-17 students",
        deadline_at=_dt(2026, 3, 1),
        deadline_summary="Contest typically spring; national selection earlier",
    ),
    _item(
        external_id="i-sweeep-environment-olympiad-2026",
        title="I-SWEEEP International STEM Olympiad",
        url="https://isweeep.org/",
        description="International sustainable energy, engineering, and environment project olympiad for middle and high school students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["biology", "engineering", "research"],
        eligible_countries=[],
        experience="Project-based; open international registration",
        deadline_at=_dt(2026, 2, 28),
        deadline_summary="Project registration typically winter",
    ),
    # —— Chemistry ——
    _item(
        external_id="singapore-junior-chemistry-olympiad-2026",
        title="Singapore Junior Chemistry Olympiad (SJChO)",
        url="https://snus.org.sg/",
        description="Junior chemistry olympiad for Singapore secondary students run with SNUS support.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["chemistry"],
        eligible_countries=["SG"],
        grade_min=7,
        grade_max=10,
        experience="Open via schools",
        deadline_at=_dt(2026, 4, 10),
        deadline_summary="Typically April",
    ),
    _item(
        external_id="canadian-chemistry-olympiad-cco-2026",
        title="Canadian Chemistry Olympiad (CCO)",
        url="https://www.cheminst.ca/",
        description="Chemical Institute of Canada olympiad pathway from the Canadian Chemistry Contest toward IChO.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["chemistry"],
        eligible_countries=["CA"],
        experience="Strong CCC score / invitation",
        deadline_at=_dt(2026, 4, 18),
        deadline_summary="National exam/camp typically spring",
    ),
    _item(
        external_id="australian-chemistry-olympiad-aso-2026",
        title="Australian Science Olympiad — Chemistry",
        url="https://www.aso.edu.au/",
        description="Australian Science Olympiad chemistry exam and summer school toward IChO selection.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["chemistry"],
        eligible_countries=["AU"],
        experience="Open national exam",
        deadline_at=_dt(2026, 8, 5),
        deadline_summary="Exam typically August",
    ),
    _item(
        external_id="south-african-chemistry-olympiad-2026",
        title="South African Chemistry Olympiad",
        url="https://www.saci.co.za/",
        description="National chemistry olympiad activities under the South African Chemical Institute.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["chemistry"],
        eligible_countries=["ZA"],
        experience="Open via schools / SACI",
        deadline_at=_dt(2026, 5, 30),
        deadline_summary="School rounds typically May–June",
    ),
    _item(
        external_id="brazilian-chemistry-olympiad-obq-2026",
        title="Brazilian Chemistry Olympiad (OBQ)",
        url="https://www.obquimica.org/",
        description="National Brazilian chemistry olympiad with multiple phases leading to IChO team selection.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["chemistry"],
        eligible_countries=["BR"],
        experience="Open via Brazilian schools",
        deadline_at=_dt(2026, 6, 20),
        deadline_summary="First phase typically mid-year",
    ),
    _item(
        external_id="chinese-chemistry-olympiad-ccho-2026",
        title="Chinese Chemistry Olympiad (CChO)",
        url="https://www.ccs.ac.cn/",
        description="National chemistry olympiad of China selecting students for IChO training.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["chemistry"],
        eligible_countries=["CN"],
        experience="Provincial selection then national final",
        deadline_at=_dt(2026, 9, 1),
        deadline_summary="Provincial rounds typically autumn",
    ),
    _item(
        external_id="rsc-chemistry-olympiad-ireland-2026",
        title="Irish Chemistry Olympiad / RSC Ireland pathway",
        url="https://www.rsc.org/",
        description="Ireland's chemistry olympiad pathway connected with Royal Society of Chemistry education programs.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["chemistry"],
        eligible_countries=["IE"],
        experience="School registration / national selection",
        deadline_at=_dt(2026, 1, 31),
        deadline_summary="National rounds typically winter–spring",
    ),
    # —— Physics ——
    _item(
        external_id="singapore-physics-olympiad-2026",
        title="Singapore Physics Olympiad (SPhO)",
        url="https://www.sps.nus.edu.sg/",
        description="National physics olympiad for Singapore students toward IPhO selection.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["physics"],
        eligible_countries=["SG"],
        experience="School nomination / open exam",
        deadline_at=_dt(2026, 6, 15),
        deadline_summary="Typically mid-year",
    ),
    _item(
        external_id="australian-physics-olympiad-aso-2026",
        title="Australian Science Olympiad — Physics",
        url="https://www.aso.edu.au/",
        description="Australian Science Olympiad physics exam leading to summer school and IPhO team selection.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["physics"],
        eligible_countries=["AU"],
        experience="Open national exam",
        deadline_at=_dt(2026, 8, 5),
        deadline_summary="Exam typically August",
    ),
    _item(
        external_id="brazilian-physics-olympiad-obf-2026",
        title="Brazilian Physics Olympiad (OBF)",
        url="https://www.sbfisica.org.br/v1/olimpiada/",
        description="Sociedade Brasileira de Física national physics olympiad for secondary students.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["physics"],
        eligible_countries=["BR"],
        experience="Open via Brazilian schools",
        deadline_at=_dt(2026, 5, 25),
        deadline_summary="First phase typically May",
    ),
    _item(
        external_id="chinese-physics-olympiad-cpho-2026",
        title="Chinese Physics Olympiad (CPhO)",
        url="https://www.cps-net.org.cn/",
        description="National physics olympiad of China in the IPhO selection pipeline.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["physics"],
        eligible_countries=["CN"],
        experience="Provincial then national selection",
        deadline_at=_dt(2026, 9, 15),
        deadline_summary="Provincial rounds typically autumn",
    ),
    _item(
        external_id="south-african-physics-olympiad-2026",
        title="South African Physics Olympiad (SPhO)",
        url="https://www.saip.org.za/",
        description="National physics olympiad under the South African Institute of Physics.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["physics"],
        eligible_countries=["ZA"],
        experience="Open via schools",
        deadline_at=_dt(2026, 8, 20),
        deadline_summary="Typically August–September",
    ),
    _item(
        external_id="eu-physics-olympiad-eupho-2026",
        title="European Physics Olympiad (EuPhO)",
        url="https://eupho.ee/",
        description="European regional physics olympiad for national teams of secondary students.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["physics"],
        eligible_countries=EU + ["GB", "CH", "NO", "IS"],
        experience="National team selection",
        deadline_at=_dt(2026, 4, 1),
        deadline_summary="Contest typically May–June; national deadlines earlier",
    ),
    # —— Engineering / robotics ——
    _item(
        external_id="world-robot-olympiad-2026",
        title="World Robot Olympiad (WRO)",
        url="https://wro-association.org/",
        description="Global robotics competition for school teams with Regular, Open, and Football categories.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["engineering", "computer-science"],
        eligible_countries=[],
        grade_min=8,
        experience="Team-based; national WRO organizers",
        deadline_at=_dt(2026, 6, 30),
        deadline_summary="National events mid-year; international final autumn",
    ),
    _item(
        external_id="shell-eco-marathon-youth-2026",
        title="Shell Eco-marathon",
        url="https://www.shellecomarathon.com/",
        description="Energy-efficiency vehicle design competition for student teams, including secondary-school divisions in some regions.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["engineering"],
        eligible_countries=[],
        experience="Team-based design/build",
        deadline_at=_dt(2026, 1, 31),
        deadline_summary="Regional registration typically winter",
    ),
    # —— Research / summer schools ——
    _item(
        external_id="michigan-math-science-scholars-2026",
        title="Michigan Math and Science Scholars (MMSS)",
        url="https://lsa.umich.edu/mmss",
        description="University of Michigan summer program with intensive math and science courses for high-school students.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["mathematics", "biology", "chemistry", "physics", "research"],
        eligible_countries=["US"],
        experience="Open application; selective",
        deadline_at=_dt(2026, 3, 15),
        deadline_summary="Applications typically due mid-March",
    ),
    _item(
        external_id="princeton-pact-algorithms-2026",
        title="Program in Algorithmic and Combinatorial Thinking (PACT)",
        url="https://algorithmicthinking.org/",
        description="Princeton-area summer program on algorithms and combinatorics for high-school students.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["computer-science", "mathematics"],
        eligible_countries=["US"],
        experience="Strong math/CS background recommended",
        deadline_at=_dt(2026, 4, 1),
        deadline_summary="Applications typically due early spring",
    ),
    _item(
        external_id="sparc-summer-program-2026",
        title="SPARC (Summer Program on Applied Rationality and Cognition)",
        url="https://sparc-camp.org/",
        description="Selective summer program on rationality, cognitive science, and applied problem-solving for talented high-school students.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["social-science", "research", "ai"],
        eligible_countries=["US"],
        experience="Highly selective application",
        deadline_at=_dt(2026, 3, 20),
        deadline_summary="Applications typically due March",
    ),
    _item(
        external_id="canada-fields-undergraduate-summer-hs-bridge-2026",
        title="Fields Institute math outreach / summer camps",
        url="https://www.fields.utoronto.ca/",
        description="Fields Institute (Toronto) outreach and summer mathematics activities open to strong high-school students.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["mathematics", "research"],
        eligible_countries=["CA"],
        experience="Varies by program",
        deadline_at=_dt(2026, 4, 30),
        deadline_summary="Summer program deadlines typically April–May",
    ),
    _item(
        external_id="nanyang-research-attachment-hs-2026",
        title="Nanyang Research Programme (NRP) / NTU youth research",
        url="https://www.ntu.edu.sg/",
        description="NTU Singapore research attachment opportunities for junior college and secondary students.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["research", "biology", "chemistry", "physics", "computer-science"],
        eligible_countries=["SG"],
        experience="School nomination / competitive application",
        deadline_at=_dt(2026, 2, 28),
        deadline_summary="Intake deadlines typically February–March",
    ),
    _item(
        external_id="csiro-vacation-scholarships-hs-path-2026",
        title="CSIRO STEM outreach / Young Indigenous STEM programs",
        url="https://www.csiro.au/en/education",
        description="CSIRO education and STEM research outreach programs for Australian secondary students.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["research", "biology", "engineering"],
        eligible_countries=["AU"],
        experience="Open / targeted cohorts",
        deadline_at=_dt(2026, 3, 31),
        deadline_summary="Program deadlines vary; many close in early autumn (AU)",
    ),
    _item(
        external_id="imperial-college-global-summer-school-2026",
        title="Imperial College London Global Summer School",
        url="https://www.imperial.ac.uk/study/schools-outreach/global-summer-school/",
        description="Residential STEM summer school at Imperial College London for international high-school students.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["engineering", "physics", "chemistry", "biology", "computer-science"],
        eligible_countries=[],
        experience="Open international application; selective",
        deadline_at=_dt(2026, 3, 1),
        deadline_summary="Applications typically close early spring",
    ),
    _item(
        external_id="oxford-unboxed-summer-schools-2026",
        title="University of Oxford UNIQ / outreach summer schools",
        url="https://www.uniq.ox.ac.uk/",
        description="Oxford UNIQ free residential summer schools for UK state-school students exploring university study.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["research", "social-science", "mathematics", "writing"],
        eligible_countries=["GB"],
        experience="UK state-school eligibility criteria apply",
        deadline_at=_dt(2026, 1, 26),
        deadline_summary="Applications typically due late January",
    ),
    _item(
        external_id="cambridge-hedp-summer-schools-2026",
        title="University of Cambridge HE+ / Sutton Trust summer schools",
        url="https://www.undergraduate.study.cam.ac.uk/events/summer-schools",
        description="Cambridge and partner outreach summer schools for UK secondary students from underrepresented backgrounds.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["research", "social-science"],
        eligible_countries=["GB"],
        experience="Eligibility criteria for outreach cohorts",
        deadline_at=_dt(2026, 2, 10),
        deadline_summary="Typically February deadlines",
    ),
    _item(
        external_id="eth-zurich-studienwochen-2026",
        title="ETH Zurich study weeks for high-school students",
        url="https://ethz.ch/en/studies/bachelor/application/high-school-students.html",
        description="ETH Zurich study weeks and taster programs introducing secondary students to STEM research.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["engineering", "physics", "mathematics", "computer-science"],
        eligible_countries=["CH"] + EU,
        experience="Open application; German/English varies by week",
        deadline_at=_dt(2026, 3, 31),
        deadline_summary="Registration typically closes in spring",
    ),
    _item(
        external_id="weizmann-dr-bessie-science-workshops-2026",
        title="Weizmann Institute Dr. Bessie F. Lawrence Summer Science Workshops",
        url="https://www.weizmann.ac.il/YoungSci/",
        description="International summer science workshops at the Weizmann Institute for outstanding high-school students.",
        opportunity_type=OT.RESEARCH_PROGRAM,
        field_slugs=["research", "biology", "chemistry", "physics"],
        eligible_countries=[],
        experience="Highly selective international application",
        deadline_at=_dt(2026, 3, 1),
        deadline_summary="Applications typically due early spring",
    ),
    # —— Writing / social science ——
    _item(
        external_id="princeton-prize-race-relations-2026",
        title="Princeton Prize in Race Relations",
        url="https://princetonprize.princeton.edu/",
        description="Princeton University prize recognizing high-school students who improve race relations in their communities.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["social-science", "writing"],
        eligible_countries=["US"],
        experience="Open nomination/application in prize regions",
        deadline_at=_dt(2026, 1, 31),
        deadline_summary="Typically late January",
    ),
    _item(
        external_id="columbia-scholastic-press-awards-2026",
        title="Columbia Scholastic Press Association Awards",
        url="https://cspa.columbia.edu/",
        description="National awards and critique for high-school newspapers, yearbooks, magazines, and digital media.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["writing"],
        eligible_countries=["US"],
        experience="School publication membership",
        deadline_at=_dt(2026, 6, 15),
        deadline_summary="Gold Circle / Crown deadlines posted annually",
    ),
    _item(
        external_id="al-neuharth-free-spirit-journalism-2026",
        title="Al Neuharth Free Spirit and Journalism Conference",
        url="https://www.freedomforum.org/",
        description="Freedom Forum journalism conference bringing high-school journalists to Washington, D.C.",
        opportunity_type=OT.FELLOWSHIP,
        field_slugs=["writing", "social-science"],
        eligible_countries=["US"],
        experience="Rising seniors; nomination/application",
        deadline_at=_dt(2026, 2, 20),
        deadline_summary="Applications typically due February",
    ),
    _item(
        external_id="jcamp-journalism-diversity-2026",
        title="JCamp (AAJA Journalism Camp)",
        url="https://www.aaja.org/",
        description="All-expenses-paid multicultural journalism camp for high-school students interested in media careers.",
        opportunity_type=OT.FELLOWSHIP,
        field_slugs=["writing"],
        eligible_countries=["US"],
        experience="Open competitive application",
        deadline_at=_dt(2026, 3, 15),
        deadline_summary="Applications typically due mid-March",
    ),
    _item(
        external_id="harvard-international-review-essay-2026",
        title="Harvard International Review Academic Writing Contest",
        url="https://hir.harvard.edu/",
        description="Global affairs essay contest for high-school students hosted by the Harvard International Review.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["writing", "social-science"],
        eligible_countries=[],
        experience="Open international",
        deadline_at=_dt(2026, 5, 31),
        deadline_summary="Contest cycles announced on HIR site",
    ),
    _item(
        external_id="canadian-citizen-youth-essay-2026",
        title="Historica Canada / Citizenship Challenge",
        url="https://www.historicacanada.ca/",
        description="Historica Canada citizenship and history challenges engaging Canadian youth with civic knowledge.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["social-science", "writing"],
        eligible_countries=["CA"],
        experience="Open via Canadian schools",
        deadline_at=_dt(2026, 2, 28),
        deadline_summary="Challenge windows typically winter–spring",
    ),
    _item(
        external_id="australia-national-history-challenge-2026",
        title="National History Challenge (Australia)",
        url="https://www.historychallenge.org.au/",
        description="Australian national history research and writing competition for primary and secondary students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["social-science", "writing"],
        eligible_countries=["AU"],
        grade_min=5,
        experience="Open via Australian schools",
        deadline_at=_dt(2026, 8, 21),
        deadline_summary="Typically August",
    ),
    # —— Business / economics ——
    _item(
        external_id="wharton-global-youth-lbw-2026",
        title="Wharton Leadership in the Business World (LBW)",
        url="https://globalyouth.wharton.upenn.edu/",
        description="Wharton Global Youth Program intensive summer business leadership program for rising seniors.",
        opportunity_type=OT.SUMMER_SCHOOL,
        field_slugs=["business", "economics"],
        eligible_countries=[],
        experience="Rising seniors; selective",
        deadline_at=_dt(2026, 2, 1),
        deadline_summary="Early deadline typically February",
    ),
    _item(
        external_id="nfte-world-series-innovation-2026",
        title="NFTE World Series of Innovation",
        url="https://www.nfte.com/",
        description="Network for Teaching Entrepreneurship challenge where students invent solutions to real corporate briefs.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["business", "engineering"],
        eligible_countries=["US"],
        experience="Open via NFTE / partner schools",
        deadline_at=_dt(2026, 11, 15),
        deadline_summary="Challenge rounds typically fall–winter",
    ),
    _item(
        external_id="young-enterprise-uk-company-2026",
        title="Young Enterprise Company Programme (UK)",
        url="https://www.young-enterprise.org.uk/",
        description="UK entrepreneurship programme where secondary students create and run real mini-companies.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["business", "economics"],
        eligible_countries=["GB"],
        experience="Via participating UK schools/colleges",
        deadline_at=_dt(2026, 9, 30),
        deadline_summary="School year programme; registration in autumn",
    ),
    _item(
        external_id="ja-company-program-canada-2026",
        title="Junior Achievement Company Program (Canada)",
        url="https://www.jacanada.org/",
        description="JA Canada entrepreneurship program where students launch ventures with mentor support.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["business"],
        eligible_countries=["CA"],
        experience="Via JA Canada partners",
        deadline_at=_dt(2026, 10, 15),
        deadline_summary="School-year cohorts; fall start common",
    ),
    _item(
        external_id="economics-olympiad-ieso-note-2026",
        title="International Economics Olympiad national selection tracks",
        url="https://ecolymp.org/",
        description="International Economics Olympiad for secondary students; enter via national olympiad organizers.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["economics", "social-science"],
        eligible_countries=[],
        experience="National selection required",
        deadline_at=_dt(2026, 4, 30),
        deadline_summary="National deadlines spring; international final summer",
    ),
    _item(
        external_id="singapore-economics-challenge-2026",
        title="National Economics Challenge / Singapore youth economics contests",
        url="https://www.ess.org.sg/",
        description="Economics Society of Singapore and partner contests for JC and secondary economics students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["economics"],
        eligible_countries=["SG"],
        experience="Via Singapore schools",
        deadline_at=_dt(2026, 5, 15),
        deadline_summary="Contest calendar typically first half of year",
    ),
    _item(
        external_id="indian-economics-olympiad-pathway-2026",
        title="Indian Economics Olympiad / IEO India pathway",
        url="https://www.ieo-official.org/",
        description="National pathway contests preparing Indian secondary students for the International Economics Olympiad.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["economics"],
        eligible_countries=["IN"],
        experience="Open national registration when offered",
        deadline_at=_dt(2026, 3, 31),
        deadline_summary="National rounds typically spring",
    ),
    # —— Scholarships / fellowships ——
    _item(
        external_id="burger-king-scholars-2026",
        title="Burger King Scholars Program",
        url="https://www.bmscholars.com/",
        description="Scholarship awards for high-school seniors and Burger King employees pursuing postsecondary education.",
        opportunity_type=OT.SCHOLARSHIP,
        field_slugs=["business"],
        eligible_countries=["US", "CA", "PR"],
        experience="Open application; seniors and employees",
        deadline_at=_dt(2026, 12, 15),
        deadline_summary="Typically mid-December",
    ),
    _item(
        external_id="equitable-excellence-scholarship-2026",
        title="Equitable Excellence Scholarship",
        url="https://equitable.com/foundation",
        description="Equitable Foundation scholarships recognizing high-school seniors for academic and community impact.",
        opportunity_type=OT.SCHOLARSHIP,
        field_slugs=["social-science", "business"],
        eligible_countries=["US"],
        experience="US high-school seniors",
        deadline_at=_dt(2026, 12, 18),
        deadline_summary="Typically mid-December",
    ),
    _item(
        external_id="foot-locker-scholars-2026",
        title="Foot Locker Scholars Athletes Program",
        url="https://www.footlockerscholars.com/",
        description="Scholarships for student-athletes balancing academics, sport, and community leadership.",
        opportunity_type=OT.SCHOLARSHIP,
        field_slugs=["social-science"],
        eligible_countries=["US"],
        experience="High-school seniors; athletic participation",
        deadline_at=_dt(2026, 12, 12),
        deadline_summary="Typically December",
    ),
    _item(
        external_id="boettcher-scholarship-2026",
        title="Boettcher Scholarship",
        url="https://boettcherfoundation.org/boettcher-scholarship/",
        description="Full-ride Colorado scholarship for outstanding graduating seniors attending Colorado colleges.",
        opportunity_type=OT.SCHOLARSHIP,
        field_slugs=["research", "social-science"],
        eligible_countries=["US"],
        experience="Colorado high-school seniors",
        deadline_at=_dt(2026, 11, 1),
        deadline_summary="Typically November 1",
    ),
    _item(
        external_id="flinn-scholars-2026",
        title="Flinn Scholarship",
        url="https://flinn.org/scholars/",
        description="Arizona's premier undergraduate scholarship with enrichment funding for top high-school seniors.",
        opportunity_type=OT.SCHOLARSHIP,
        field_slugs=["research", "social-science"],
        eligible_countries=["US"],
        experience="Arizona high-school seniors",
        deadline_at=_dt(2026, 10, 15),
        deadline_summary="Typically mid-October",
    ),
    _item(
        external_id="posse-foundation-scholars-2026",
        title="Posse Foundation Scholars Program",
        url="https://www.possefoundation.org/",
        description="Full-tuition leadership scholarships placing diverse student cohorts at partner universities.",
        opportunity_type=OT.SCHOLARSHIP,
        field_slugs=["social-science"],
        eligible_countries=["US"],
        experience="Nomination via Posse cities; seniors",
        deadline_at=_dt(2026, 8, 15),
        deadline_summary="Nomination deadlines typically August–September",
    ),
    _item(
        external_id="stamps-scholars-2026",
        title="Stamps Scholars Program",
        url="https://www.stampsfoundation.org/",
        description="Merit scholarships with enrichment funds at partner universities for exceptional students.",
        opportunity_type=OT.SCHOLARSHIP,
        field_slugs=["research", "social-science"],
        eligible_countries=["US"],
        experience="Apply via partner university admissions",
        deadline_at=_dt(2026, 11, 15),
        deadline_summary="Deadlines follow partner university early applications",
    ),
    _item(
        external_id="hispanic-scholarship-fund-2026",
        title="Hispanic Scholarship Fund Scholarships",
        url="https://www.hsf.net/",
        description="HSF scholarships supporting Hispanic American high-school seniors and college students.",
        opportunity_type=OT.SCHOLARSHIP,
        field_slugs=["social-science", "business"],
        eligible_countries=["US", "PR"],
        experience="Open to eligible Hispanic students",
        deadline_at=_dt(2026, 2, 15),
        deadline_summary="HSF General Scholarship typically mid-February",
    ),
    _item(
        external_id="jackie-robinson-foundation-2026",
        title="Jackie Robinson Foundation Scholarship",
        url="https://jackierobinson.org/",
        description="Multi-year scholarship and leadership program for minority high-school seniors pursuing college.",
        opportunity_type=OT.SCHOLARSHIP,
        field_slugs=["social-science"],
        eligible_countries=["US"],
        experience="Minority graduating seniors; financial need",
        deadline_at=_dt(2026, 1, 9),
        deadline_summary="Typically early January",
    ),
    _item(
        external_id="scholarship-america-dream-award-2026",
        title="Scholarship America Dream Award",
        url="https://scholarshipamerica.org/",
        description="Renewable awards supporting high-achieving students with financial need through college.",
        opportunity_type=OT.SCHOLARSHIP,
        field_slugs=["social-science"],
        eligible_countries=["US"],
        experience="US students with financial need",
        deadline_at=_dt(2026, 10, 31),
        deadline_summary="Typically fall application window",
    ),
    # —— More STEM competitions & olympiads ——
    _item(
        external_id="international-astronomy-olympiad-iao-2026",
        title="International Astronomy Olympiad (IAO)",
        url="https://www.issp.ac.ru/iao/",
        description="International olympiad in astronomy for secondary students selected by national astronomy olympiad programs.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["physics"],
        eligible_countries=[],
        experience="National team selection",
        deadline_at=_dt(2026, 5, 1),
        deadline_summary="National selection spring; IAO typically autumn",
    ),
    _item(
        external_id="international-earth-science-olympiad-ieso-2026",
        title="International Earth Science Olympiad (IESO)",
        url="https://www.ieso-info.org/",
        description="International olympiad covering geology, meteorology, oceanography, and environmental science.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["biology", "physics", "research"],
        eligible_countries=[],
        experience="National team selection",
        deadline_at=_dt(2026, 4, 15),
        deadline_summary="National deadlines spring; IESO typically August–September",
    ),
    _item(
        external_id="international-geography-olympiad-igeo-2026",
        title="International Geography Olympiad (iGeo)",
        url="https://www.geoolympiad.org/",
        description="International geography olympiad for secondary students with written, multimedia, and fieldwork tests.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["social-science"],
        eligible_countries=[],
        experience="National geography olympiad selection",
        deadline_at=_dt(2026, 3, 31),
        deadline_summary="National selection spring; iGeo typically summer",
    ),
    _item(
        external_id="international-linguistics-olympiad-iol-2026",
        title="International Linguistics Olympiad (IOL)",
        url="https://www.ioling.org/",
        description="International olympiad in linguistics for secondary students; no prior linguistics coursework required.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["social-science", "writing"],
        eligible_countries=[],
        experience="National linguistics olympiad selection",
        deadline_at=_dt(2026, 4, 1),
        deadline_summary="National contests winter–spring; IOL typically July",
    ),
    _item(
        external_id="international-philosophy-olympiad-ipo-2026",
        title="International Philosophy Olympiad (IPO)",
        url="https://www.philosophy-olympiad.org/",
        description="UNESCO-affiliated philosophy essay olympiad for high-school students selected nationally.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["social-science", "writing"],
        eligible_countries=[],
        experience="National philosophy olympiad selection",
        deadline_at=_dt(2026, 3, 15),
        deadline_summary="National selection early spring; IPO typically May",
    ),
    _item(
        external_id="chinese-mathematical-olympiad-cmo-2026",
        title="Chinese Mathematical Olympiad (CMO)",
        url="https://www.cms.org.cn/",
        description="National mathematics olympiad of China selecting students for IMO training.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["CN"],
        experience="Provincial olympiad qualification",
        deadline_at=_dt(2026, 11, 20),
        deadline_summary="Typically late November",
    ),
    _item(
        external_id="hong-kong-math-olympiad-hkmo-2026",
        title="Hong Kong Mathematical Olympiad (HKMO)",
        url="https://www.hkage.org.hk/",
        description="Hong Kong mathematics olympiad pathway for secondary students toward IMO selection.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["HK"],
        experience="Via HK schools / HKAGE",
        deadline_at=_dt(2026, 12, 5),
        deadline_summary="Heat rounds typically December",
    ),
    _item(
        external_id="new-zealand-maths-olympiad-2026",
        title="New Zealand Mathematical Olympiad",
        url="https://www.mathsolympiad.org.nz/",
        description="NZ maths olympiad camps and contests selecting the IMO team.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["NZ"],
        experience="Open contests then invitation camps",
        deadline_at=_dt(2026, 5, 31),
        deadline_summary="Year-round training; camp applications mid-year",
    ),
    _item(
        external_id="irish-mathematical-olympiad-2026",
        title="Irish Mathematical Olympiad (IrMO)",
        url="https://www.irmo.ie/",
        description="Ireland's national mathematics olympiad for secondary students toward IMO selection.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["IE"],
        experience="Open via Irish schools",
        deadline_at=_dt(2026, 4, 25),
        deadline_summary="Typically April (IrMO paper)",
    ),
    _item(
        external_id="polish-math-olympiad-om-2026",
        title="Polish Mathematical Olympiad (OM)",
        url="https://om.ptm.org.pl/",
        description="Olimpiada Matematyczna — Poland's national math olympiad with a long IMO tradition.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["PL"],
        experience="Open via Polish schools",
        deadline_at=_dt(2026, 9, 10),
        deadline_summary="First stage typically September",
    ),
    _item(
        external_id="german-math-olympiad-bmo-landes-2026",
        title="German Mathematical Olympiad (Bundesrunde)",
        url="https://www.mathematik-olympiaden.de/",
        description="Germany's multi-round mathematics olympiad culminating in the national Bundesrunde.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["DE"],
        experience="School → regional → national rounds",
        deadline_at=_dt(2026, 11, 12),
        deadline_summary="School round typically November",
    ),
    _item(
        external_id="french-concours-general-maths-2026",
        title="Concours général — Mathematics (France)",
        url="https://www.education.gouv.fr/",
        description="France's Concours général excellence contest including a prestigious mathematics paper for lycée students.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["mathematics"],
        eligible_countries=["FR"],
        experience="Via French lycées; teacher nomination",
        deadline_at=_dt(2026, 3, 20),
        deadline_summary="Typically March",
    ),
    _item(
        external_id="spanish-olympiad-matematica-2026",
        title="Spanish Mathematical Olympiad (OME)",
        url="https://www.olimpiadamatematica.es/",
        description="Olimpiada Matemática Española selecting Spain's IMO team through district and national phases.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["ES"],
        experience="Via Spanish schools / RSME",
        deadline_at=_dt(2026, 1, 17),
        deadline_summary="Local phases typically January",
    ),
    _item(
        external_id="italian-math-olympiad-olimpiadi-2026",
        title="Italian Mathematical Olympiad (Olimpiadi di Matematica)",
        url="https://olym.dm.unipi.it/",
        description="Italian math olympiad stages (Canguro, Giochi di Archimede, Cesenatico) toward IMO selection.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["IT"],
        experience="Open school stages then invitation",
        deadline_at=_dt(2026, 11, 20),
        deadline_summary="Archimede stage typically November",
    ),
    _item(
        external_id="korean-math-olympiad-kmo-2026",
        title="Korean Mathematical Olympiad (KMO)",
        url="https://www.kms.or.kr/",
        description="Korean Mathematical Society olympiad selecting students for IMO training.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["KR"],
        experience="School registration / KMO rounds",
        deadline_at=_dt(2026, 5, 16),
        deadline_summary="First round typically May",
    ),
    _item(
        external_id="japan-math-olympiad-jmo-2026",
        title="Japan Mathematical Olympiad (JMO)",
        url="https://www.imojp.org/",
        description="Japanese Mathematical Olympiad pathway toward IMO team selection.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["JP"],
        experience="Open qualifying then JMO final",
        deadline_at=_dt(2026, 1, 12),
        deadline_summary="Qualifying typically January",
    ),
    _item(
        external_id="taiwan-primary-secondary-math-olympiad-2026",
        title="Taiwan Primary and Secondary Mathematics Competitions / IMO pathway",
        url="https://www.tms.org.tw/",
        description="Taiwan Mathematical Society contests feeding the IMO selection pipeline for secondary students.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["TW"],
        experience="Via Taiwan schools",
        deadline_at=_dt(2026, 9, 20),
        deadline_summary="National rounds typically autumn",
    ),
    _item(
        external_id="thailand-math-olympiad-posn-2026",
        title="Thailand POSN Mathematical Olympiad camps",
        url="https://www.posn.or.th/",
        description="POSN academic olympiad centers in Thailand training secondary students for IMO and other science olympiads.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics", "physics", "chemistry", "biology", "computer-science"],
        eligible_countries=["TH"],
        experience="School nomination to POSN centres",
        deadline_at=_dt(2026, 6, 30),
        deadline_summary="Centre exams mid-year",
    ),
    _item(
        external_id="vietnam-math-olympiad-vmo-2026",
        title="Vietnam Mathematical Olympiad (VMO)",
        url="https://www.vnims.vn/",
        description="National mathematics olympiad of Vietnam selecting students for IMO and regional contests.",
        opportunity_type=OT.OLYMPIAD,
        field_slugs=["mathematics"],
        eligible_countries=["VN"],
        experience="Provincial then national selection",
        deadline_at=_dt(2026, 12, 26),
        deadline_summary="National exam typically late December",
    ),
    _item(
        external_id="cern-beamline-for-schools-2026",
        title="CERN Beamline for Schools",
        url="https://beamline-for-schools.cern/",
        description="Competition where high-school teams propose particle-physics experiments; winners run them at a CERN beamline.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["physics", "research", "engineering"],
        eligible_countries=[],
        experience="Team proposal; open worldwide",
        deadline_at=_dt(2026, 3, 31),
        deadline_summary="Proposals typically due end of March",
    ),
    _item(
        external_id="esa-climate-detective-schools-2026",
        title="ESA Climate Detectives",
        url="https://climatedetectives.esa.int/",
        description="European Space Agency school project where teams investigate local climate problems using satellite data.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["physics", "biology", "research"],
        eligible_countries=EU + ["GB", "NO", "CH", "IS", "CA"],
        grade_min=6,
        experience="School teams ages ~8–19",
        deadline_at=_dt(2026, 4, 24),
        deadline_summary="Investigation phase typically closes late April",
    ),
    _item(
        external_id="nasa-techrise-student-challenge-2026",
        title="NASA TechRise Student Challenge",
        url="https://www.nasa.gov/learning-resources/techrise/",
        description="NASA challenge for student teams to design experiments flying on suborbital vehicles or high-altitude balloons.",
        opportunity_type=OT.COMPETITION,
        field_slugs=["engineering", "physics", "research"],
        eligible_countries=["US"],
        grade_min=6,
        experience="Team-based; middle and high school",
        deadline_at=_dt(2026, 11, 13),
        deadline_summary="Typically mid-November",
    ),

]


def seed_solid_programs_catalog(db: Session) -> dict[str, int]:
    """Upsert solid programs catalog entries (automated update check each run)."""
    stats = {"listed": 0, "created": 0, "updated": 0, "skipped": 0, "no_deadline": 0}

    items = SOLID_PROGRAMS_CATALOG
    stats["listed"] = len(items)
    logger.info("Seeding %s — %s opportunit(ies)", SOURCE_NAME, len(items))

    for index, item in enumerate(items, start=1):
        try:
            if item.deadline_at is None:
                stats["no_deadline"] += 1
            _, created = upsert_opportunity(db, item, source_name=SOURCE_NAME)
            if created:
                stats["created"] += 1
            else:
                stats["updated"] += 1
            logger.info(
                "[%s/%s] %s %s",
                index,
                len(items),
                "CREATED" if created else "UPDATED",
                item.title,
            )
        except Exception:
            stats["skipped"] += 1
            logger.exception("Failed to seed %s", item.external_id)

    return stats
