"""Curated better deadline/application pages for catalog opportunities.

Landing pages often lack labeled dates. Prefer these when enriching.
Keys are Opportunity.external_id values.
"""

from __future__ import annotations

# external_id -> ordered list of pages that usually publish deadlines
DEADLINE_PAGE_OVERRIDES: dict[str, list[str]] = {
    # Math
    "amc-12": ["https://maa.org/amcreg/", "https://maa.org/student-programs/amc/"],
    "amc-10": ["https://maa.org/amcreg/", "https://maa.org/student-programs/amc/"],
    "aime": ["https://maa.org/amcreg/", "https://maa.org/math-competitions/american-invitational-mathematics-examination-aime"],
    "usamo": ["https://maa.org/student-programs/amc/"],
    "hmmtt": ["https://www.hmmt.org/", "https://www.hmmt.org/www/tournaments"],
    "promys": ["https://promys.org/programs/promys/apply/", "https://promys.org/"],
    "ross-mathematics": ["https://rossprogram.org/"],
    "math-prize-for-girls": ["https://mathprize.atfoundation.org/"],
    "pumac": ["https://pumac.princeton.edu/"],
    "cmimc": ["https://cmimc.math.cmu.edu/"],
    "sumac": ["https://sumac.stanford.edu/"],
    "mathcamp": ["https://www.mathcamp.org/"],
    "cemc-contests": ["https://www.cemc.uwaterloo.ca/contests/contests.html"],
    "ukmt-senior-challenge": ["https://www.ukmt.org.uk/competitions"],
    "math-kangaroo": ["https://mathkangaroo.org/"],
    "arml": ["https://www.arml.com/"],
    "purple-comet": ["https://purplecomet.org/"],
    "caribou-math": ["https://www.cariboutests.com/"],
    "himcm": ["https://www.comap.com/highschool/contests/himcm/"],
    "mathworks-math-modeling": ["https://m3challenge.siam.org/"],
    # CS / AI
    "usaco": ["https://usaco.org/"],
    "picoctf": ["https://picoctf.org/"],
    "acsl": ["https://www.acsl.org/"],
    "congressional-app": ["https://www.congressionalappchallenge.us/"],
    "technovation-girls": ["https://www.technovation.org/"],
    "girls-who-code-sip": ["https://girlswhocode.com/programs/summer-immersion-program"],
    "kode-with-klossy": ["https://www.kodewithklossy.com/"],
    "ai4all": ["https://ai-4-all.org/"],
    "mit-battlecode": ["https://battlecode.org/"],
    "cyberstart-america": ["https://www.cyberstartamerica.org/"],
    "ncl": ["https://nationalcyberleague.org/"],
    "kaggle-competitions": ["https://www.kaggle.com/competitions"],
    "advent-of-code": ["https://adventofcode.com/"],
    # Physics / chem / bio
    "uspho": ["https://www.aapt.org/physicsteam/"],
    "fma": ["https://www.aapt.org/physicsteam/2026/"],
    "physics-bowl": ["https://www.aapt.org/Programs/contests/physicsbowl.cfm"],
    "usnco": ["https://www.acs.org/education/students/highschool/olympiad.html"],
    "usabo": ["https://www.usabo-trc.org/"],
    "brain-bee": ["https://thebrainbee.org/"],
    "genes-in-space": ["https://www.genesinspace.org/"],
    "ssp-astrophysics": ["https://summerscience.org/"],
    "ssp-biochem": ["https://summerscience.org/"],
    "ssp-genomics": ["https://summerscience.org/"],
    # Research / STS / fairs
    "regeneron-sts": ["https://www.societyforscience.org/regeneron-sts/"],
    "jshs": ["https://www.jshs.org/"],
    "isef": ["https://www.societyforscience.org/isef/"],
    "regeneron-isef-affiliates": ["https://www.societyforscience.org/isef/"],
    "thermo-fisher-jic": ["https://www.societyforscience.org/jic/"],
    "breakthrough-junior-challenge": ["https://breakthroughjuniorchallenge.org/"],
    "mit-primes": ["https://math.mit.edu/research/highschool/primes/"],
    "rsi-css": ["https://www.cee.org/programs/research-science-institute"],
    "mit-think": ["https://think.mit.edu/"],
    "nyas-junior-academy": ["https://www.nyas.org/programs/the-junior-academy/"],
    "pioneer-academics": ["https://pioneeracademics.com/"],
    "lumiere-research": ["https://www.lumiere-education.com/"],
    "polygence": ["https://www.polygence.org/"],
    "nih-summer-internship": ["https://www.training.nih.gov/research-training/hb/hs/"],
    "broad-summer-scholars": ["https://www.broadinstitute.org/bsip"],
    "simons-summer": ["https://www.stonybrook.edu/simons/"],
    "garcia-stony-brook": ["https://www.stonybrook.edu/commcms/garcia/"],
    "clark-scholars": ["https://www.depts.ttu.edu/honors/academicsandenrichment/affiliatedandhighschool/clarks/"],
    "iowa-sstp": ["https://belinblank.education.uiowa.edu/students/sstp/"],
    # Engineering / robotics
    "first-robotics": ["https://www.firstinspires.org/robotics/frc"],
    "first-tech-challenge": ["https://www.firstinspires.org/robotics/ftc"],
    "first-lego-league": ["https://www.firstlegoleague.org/"],
    "vex-robotics": ["https://www.vexrobotics.com/competition"],
    "team-america-rocketry": ["https://rocketcontest.org/"],
    "zero-robotics": ["http://zerorobotics.mit.edu/"],
    "conrad-challenge": ["https://www.conradchallenge.org/"],
    "nasa-space-apps": ["https://www.spaceappschallenge.org/"],
    "nasa-hunch": ["https://nasahunch.com/"],
    "nasa-sees": ["https://www.csr.utexas.edu/education/sees/"],
    # Summer / precollege
    "mites": ["https://oeop.mit.edu/programs/mites"],
    "yale-yygs": ["https://globalscholars.yale.edu/"],
    "telluride-tass": ["https://www.tellurideassociation.org/"],
    "cosmos-uc": ["https://cosmos.ucop.edu/"],
    "cmu-sams": ["https://www.cmu.edu/pre-college/academic-programs/sams.html"],
    "mit-bwsi": ["https://beaverworks.ll.mit.edu/CMS/bw/bwsi"],
    "stanford-shtem": ["https://shtem.stanford.edu/"],
    "bank-of-america-student-leaders": ["https://about.bankofamerica.com/en/making-an-impact/student-leaders"],
    # Writing / humanities
    "scholastic-art-writing": ["https://www.artandwriting.org/"],
    "bennington-young-writers": ["https://www.bennington.edu/events/young-writers-awards"],
    "princeton-poetry": ["https://princeton.edu/"],
    "profile-in-courage": ["https://www.jfklibrary.org/Education/Profile-in-Courage-Essay-Contest.aspx"],
    "john-locke-essay": ["https://www.johnlockeinstitute.com/essay-competition"],
    "foyle-young-poets": ["https://foyleyoungpoets.org/"],
    "concord-review": ["https://www.tcr.org/"],
    "nyt-student-editorial": ["https://www.nytimes.com/spotlight/learning-student-contests"],
    "nyt-personal-narrative": ["https://www.nytimes.com/spotlight/learning-student-contests"],
    "bow-seat-ocean-awareness": ["https://bowseat.org/programs/ocean-awareness-contest/"],
    "youngarts": ["https://www.youngarts.org/"],
    "poetry-out-loud": ["https://www.poetryoutloud.org/"],
    "national-history-day": ["https://www.nhd.org/"],
    "cspan-studentcam": ["https://www.studentcam.org/"],
    # Business / econ
    "diamond-challenge": ["https://diamondchallenge.org/"],
    "blue-ocean-competition": ["https://blueoceancompetition.org/"],
    "wharton-investment-competition": ["https://globalyouth.wharton.upenn.edu/contests-competitions/investment-competition/"],
    "deca": ["https://www.deca.org/"],
    "fbla": ["https://www.fbla.org/"],
    "nec": ["https://www.councilforeconed.org/national-economics-challenge/"],
    "modeling-the-future": ["https://www.mtfchallenge.org/"],
    # Scholarships
    "questbridge": ["https://www.questbridge.org/high-school-students"],
    "coca-cola-scholars": ["https://www.coca-colascholarsfoundation.org/"],
    "davidson-fellows": ["https://www.davidsongifted.org/gifted-programs/davidson-fellows/"],
    "gates-scholarship": ["https://www.thegatesscholarship.org/scholarship"],
    "jack-kent-cooke-college": ["https://www.jkcf.org/our-scholarships/college-scholarship-program/"],
    "coolidge-scholarship": ["https://coolidgescholars.org/"],
    "davidson-fellows-note": ["https://coolidgescholars.org/"],
    "national-merit": ["https://www.nationalmerit.org/"],
    "dell-scholars": ["https://www.dellscholars.org/"],
    "horatio-alger": ["https://scholars.horatioalger.org/"],
    "ron-brown-scholar": ["https://www.ronbrown.org/"],
    "cameron-impact": ["https://www.bryancameroneducationfoundation.org/cameron-impact-scholarship"],
    "bold-org-scholarships": ["https://bold.org/scholarships/"],
    "nsli-y": ["https://www.nsliforyouth.org/"],
    # Misc competitions
    "naclo": ["https://naclo.org/"],
    "science-olympiad": ["https://www.soinc.org/"],
    "cyberpatriot": ["https://www.uscyberpatriot.org/"],
    "hosa": ["https://hosa.org/"],
    "genius-olympiad": ["https://www.geniusolympiad.org/"],
    "paradigm-challenge": ["https://www.projectparadigm.org/"],
    "sejong-writing": ["https://www.sejongculturalsociety.org/writing/current/index.php"],
    "national-latin-exam": ["https://www.nle.org/"],
    "future-problem-solving": ["https://www.fpspi.org/"],
    "world-scholars-cup": ["https://www.worldscholarscup.com/"],
    "ethics-bowl": ["https://nhseb.unc.edu/"],
}
